#!/usr/bin/env node
// Validate + merge the bookmark data files into one all.js, and report stats.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
// Auto-discover any data-*.js so new topic groups need no edits here.
const files = readdirSync(here).filter((f) => /^data-\d+.*\.js$/.test(f)).sort();

const all = [];
for (const f of files) {
  const src = readFileSync(join(here, f), 'utf8');
  const m = src.match(/const\s+(BOOKMARKS_\d+)\s*=\s*([\s\S]*);\s*$/);
  if (!m) {
    console.error(`FAIL: could not find array in ${f}`);
    process.exit(1);
  }
  let arr;
  try {
    arr = new Function(`${m[1]} = ${m[2]}; return ${m[1]};`)();
  } catch (e) {
    console.error(`FAIL: ${f} does not parse -> ${e.message}`);
    process.exit(1);
  }
  console.log(`${f.padEnd(28)} ${String(arr.length).padStart(4)} entries  (${m[1]})`);
  all.push(...arr);
}

// ---- validation ----
const errors = [];
const seen = new Map();
for (const [i, b] of all.entries()) {
  const where = `#${i} ${b?.t ?? '(no title)'}`;
  if (!b || typeof b !== 'object') { errors.push(`${where}: not an object`); continue; }
  for (const k of ['c', 't', 'u', 'd', 'g']) {
    if (b[k] === undefined) errors.push(`${where}: missing "${k}"`);
  }
  if (b.u && !/^https?:\/\/[^\s"'<>]+$/.test(b.u)) errors.push(`${where}: bad url "${b.u}"`);
  if (b.t && (seen.has(b.t) || seen.has(b.u))) {
    errors.push(`${where}: duplicate of "${seen.get(b.t) ?? seen.get(b.u)}"`);
  }
  if (b.t) seen.set(b.t, b.t);
  if (b.u) seen.set(b.u, b.t);
}

if (errors.length) {
  console.error(`\n${errors.length} validation problem(s):`);
  for (const e of errors) console.error('  - ' + e);
  process.exit(1);
}

// ---- sort: category, then title ----
all.sort((a, b) => a.c.localeCompare(b.c) || a.t.localeCompare(b.t));

const cats = [...new Set(all.map((b) => b.c))].sort();
const tags = [...new Set(all.flatMap((b) => b.g))].sort();
const domains = new Set(all.map((b) => new URL(b.u).hostname));

writeFileSync(
  join(here, 'all.js'),
  `// GENERATED by build.mjs - do not edit by hand.\n` +
    `// ${all.length} bookmarks across ${cats.length} categories and ${tags.length} tags.\n` +
    `const BOOKMARKS = ${JSON.stringify(all, null, 0)};\n` +
    `const CATEGORIES = ${JSON.stringify(cats)};\n` +
    `const TAGS = ${JSON.stringify(tags)};\n`
);

console.log(`\nTOTAL: ${all.length} bookmarks`);
console.log(`  categories: ${cats.length}`);
console.log(`  tags: ${tags.length}`);
console.log(`  unique domains: ${domains.size}`);
console.log('\nPer category:');
for (const c of cats) {
  console.log(`  ${c.padEnd(24)} ${String(all.filter((b) => b.c === c).length).padStart(4)}`);
}
console.log('\nWrote all.js');
