// Part 18: filling the gaps — robotics, formal methods, math, data eng,
// web perf, self-taught learning, tech pioneers, database internals
const BOOKMARKS_18 = [
  // ================================================================ Robotics & Control
  { c: "Robotics & Control", t: "Underactuated Robotics (MIT, free book)", u: "https://underactuated.mit.edu/", d: "A free, excellent MIT textbook on nonlinear control and legged robots.", g: ["robotics", "control", "books", "free", "must-read"] },
  { c: "Robotics & Control", t: "State Estimation for Robotics (Barfoot, free)", u: "https://www.robotics.ox.ac.uk/~vgg/book/", d: "A free, rigorous book on Bayesian state estimation and SLAM. Outstanding.", g: ["robotics", "slam", "books", "free", "must-read"] },
  { c: "Robotics & Control", t: "Probabilistic Robotics (Thrun, free PDF)", u: "https://www.probabilistic-robotics.org/", d: "The definitive SLAM textbook, free official PDFs per chapter. Landmark.", g: ["robotics", "slam", "books", "free", "must-read"] },
  { c: "Robotics & Control", t: "SLAM for Dummies (free)", u: "https://slamfordummies.com/", d: "A free, gentle introduction to SLAM. Perfect if the math is intimidating.", g: ["robotics", "slam", "books", "free", "must-do"] },
  { c: "Robotics & Control", t: "Caltech CDS — control systems", u: "https://murray.cds.caltech.edu/", d: "Free control systems course notes with MATLAB and Python exercises.", g: ["control", "courses", "free", "must-do"] },
  { c: "Robotics & Control", t: "ROS 2 documentation (free)", u: "https://docs.ros.org/en/rolling/", d: "The free official ROS 2 docs. The standard robotics framework.", g: ["robotics", "docs", "free", "must-use"] },
  { c: "Robotics & Control", t: "Gazebo simulator documentation", u: "https://gazebosim.org/docs", d: "Free docs for the Gazebo robot simulator.", g: ["robotics", "simulator", "free"] },
  { c: "Robotics & Control", t: "PX4 autopilot documentation", u: "https://docs.px4.io/", d: "Free docs for the PX4 open-source drone autopilot. Very well written.", g: ["robotics", "drones", "docs", "free", "must-use"] },
  { c: "Robotics & Control", t: "ArduPilot documentation (free)", u: "https://ardupilot.org/dev/docs/", d: "Free developer docs for ArduPilot, the open drone autopilot.", g: ["robotics", "drones", "docs", "free"] },
  { c: "Robotics & Control", t: "OpenCV documentation (free)", u: "https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html", d: "The free official OpenCV docs. Computer vision for everyone.", g: ["vision", "docs", "free", "must-use"] },
  { c: "Robotics & Control", t: "Open Robotics Middleware: ROS index", u: "https://www.ros.org/", d: "Free site for ROS ecosystem, distributions and community.", g: ["robotics", "community"] },
  { c: "Robotics & Control", t: "Modern Robotics (free course)", u: "https://modernrobotics.northwestern.edu/", d: "A free Coursera course from Northwestern covering grasping, planning and control.", g: ["robotics", "courses", "free", "must-do"] },
  { c: "Robotics & Control", t: "nuScenes dataset (free)", u: "https://www.nuscenes.org/", d: "A free, large-scale autonomous driving dataset from Boston and Singapore.", g: ["data", "vision", "free", "must-try"] },
  { c: "Robotics & Control", t: "KITTI Vision Benchmark (free)", u: "https://www.cvlibs.net/datasets/kitti/", d: "The free classic dataset for driving vision research.", g: ["data", "vision", "free"] },
  { c: "Robotics & Control", t: "Oxford RobotCar dataset (free)", u: "https://robotcar-dataset.robots.ox.ac.uk/", d: "A free large-scale urban driving dataset from Oxford.", g: ["data", "vision", "free"] },
  { c: "Robotics & Control", t: "Free control theory references (MIT OCW)", u: "https://ocw.mit.edu/search/?d=control+systems", d: "Free MIT control systems course materials. Browse the whole list.", g: ["control", "courses", "directory", "must-use"] },
  { c: "Robotics & Control", t: "Kalman and Bayesian Filters in Python", u: "https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python", d: "A free book as a Jupyter notebook. The clearest Kalman filter tutorial.", g: ["filtering", "python", "books", "free", "must-do"] },
  { c: "Robotics & Control", t: "OpenAI Gym / Gymnasium docs", u: "https://gymnasium.farama.org/", d: "Free reinforcement learning environment docs. The standard for RL research.", g: ["rl", "docs", "free", "must-use"] },

  // ================================================================ Formal Methods
  { c: "Formal Methods", t: "TLA+ — Lamport's specification language", u: "https://lamport.azurewebsites.net/tla/tla.html", d: "The free official TLA+ home. Learn to specify concurrent and distributed systems.", g: ["formal", "free", "must-know"] },
  { c: "Formal Methods", t: "TLA+ Toolbox (free download)", u: "https://lamport.azurewebsites.net/tla/toolbox.html", d: "The free TLA+ model checker and editor. Powerful and worth learning.", g: ["formal", "tooling", "free", "must-try"] },
  { c: "Formal Methods", t: "Dafny — verification language", u: "https://dafny.org/", d: "A free language with built-in verification. Much easier to learn than Coq.", g: ["formal", "tooling", "free", "must-try"] },
  { c: "Formal Methods", t: "Why3 — verification platform", u: "https://www.why3.org/", d: "A free verification platform with many provers. Used by Airbus.", g: ["formal", "tooling", "free"] },
  { c: "Formal Methods", t: "Frama-C — C verification (free)", u: "https://frama-c.com/", d: "A free open-source toolset for verifying C code with weakest preconditions.", g: ["formal", "c", "tooling", "open-source", "must-try"] },
  { c: "Formal Methods", t: "CBMC bounded model checker (free)", u: "https://www.cprover.org/cbmc/", d: "A free open-source bounded model checker for C and C++. Very useful.", g: ["formal", "tooling", "open-source"] },
  { c: "Formal Methods", t: "Alloy Analyzer (free)", u: "https://alloytools.org/", d: "A free relational model finder. Excellent for protocol and data modelling.", g: ["formal", "tooling", "free", "must-try"] },
  { c: "Formal Methods", t: "UPPAAL (free)", u: "https://www.uppaal.org/", d: "A free model checker for timed systems. Used in industry.", g: ["formal", "tooling", "free"] },
  { c: "Formal Methods", t: "SPIN model checker (free)", u: "https://spinroot.com/spin/Man/", d: "The free original model checker for concurrent systems. Classic.", g: ["formal", "tooling", "free", "history"] },
  { c: "Formal Methods", t: "SMT-LIB benchmarks", u: "https://smt-lib.org/", d: "The free standard benchmark suite for SMT solvers. Useful reference.", g: ["formal", "reference", "free"] },

  // ================================================================ Mathematics
  { c: "Mathematics", t: "The Book of Proof (Hammack, free)", u: "https://bookofproofs.github.io/", d: "A free, excellent book on mathematical proof. The best place to start.", g: ["math", "books", "free", "must-read"] },
  { c: "Mathematics", t: "Topology Without Tears (free)", u: "https://www.topologywithouttears.net/", d: "A free point-set topology textbook. Surprisingly gentle and rigorous.", g: ["math", "books", "free", "must-read"] },
  { c: "Mathematics", t: "Analysis I (Terence Tao, free)", u: "https://www.math.ucla.edu/~tao/analysis1/", d: "A free rigorous intro to real analysis. Plus Tao's Analysis II and measure theory.", g: ["math", "analysis", "books", "free", "must-read"] },
  { c: "Mathematics", t: "Terence Tao's blog", u: "https://terrytao.wordpress.com/", d: "Free writing on analysis, number theory and research maths. Very deep.", g: ["math", "blog", "advanced", "must-read"] },
  { c: "Mathematics", t: "Abstract Algebra: Theory and Applications (free)", u: "https://abstract.ups.edu/", d: "A free complete abstract algebra textbook with exercises and solutions.", g: ["math", "algebra", "books", "free", "must-do"] },
  { c: "Mathematics", t: "MathWorld (Wolfram, free)", u: "https://mathworld.wolfram.com/", d: "The best free maths encyclopedia. Look up any theorem, constant or identity.", g: ["math", "reference", "must-use", "free"] },
  { c: "Mathematics", t: "MIT 18.01 — Single Variable Calculus", u: "https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/", d: "A free MIT calculus course with full video lectures. Excellent.", g: ["math", "calculus", "courses", "free", "must-do"] },
  { c: "Mathematics", t: "MIT 18.02 — Multivariable Calculus", u: "https://ocw.mit.edu/courses/18-02sc-multivariable-calculus-fall-2010/", d: "A free MIT multivariable calculus course with videos. Rigorous.", g: ["math", "calculus", "courses", "free"] },
  { c: "Mathematics", t: "MIT 18.03 — Differential Equations", u: "https://ocw.mit.edu/courses/18-03sc-differential-equations-fall-2011/", d: "A free MIT differential equations course with video lectures.", g: ["math", "courses", "free"] },
  { c: "Mathematics", t: "MIT 18.100 — Real Analysis", u: "https://ocw.mit.edu/courses/18-100a-real-analysis-fall-2020/", d: "A free MIT real analysis course. Rigorous, with good problem sets.", g: ["math", "analysis", "courses", "free", "advanced"] },
  { c: "Mathematics", t: "An Introduction to Statistical Learning (free)", u: "https://www.statlearning.com/", d: "The free official site for ISLR. A classic intro ML/stats textbook.", g: ["statistics", "books", "free", "must-read"] },
  { c: "Mathematics", t: "Cut-the-Knot (free)", u: "https://www.cut-the-knot.org/", d: "Free interactive maths applets and essays. Old-school and excellent.", g: ["math", "visualization", "free", "fun"] },
  { c: "Mathematics", t: "SymPy documentation (free)", u: "https://docs.sympy.org/latest/index.html", d: "The free SymPy docs. Symbolic maths in Python, ideal for learning.", g: ["math", "python", "tooling", "free", "must-use"] },
  { c: "Mathematics", t: "Mathematica Stack Exchange (free)", u: "https://mathematica.stackexchange.com/", d: "Free Q&A for CAS systems. Very helpful for Mathematica/SymPy.", g: ["math", "community", "free"] },
  { c: "Mathematics", t: "Fedor Petrov's blog", u: "https://fedorpetrov.com/", d: "Free blog on combinatorics, algorithms and open problems. Very strong.", g: ["math", "algorithms", "blog", "must-read"] },
  { c: "Mathematics", t: "Wolfram Demonstrations Project", u: "https://demonstrations.wolfram.com/", d: "Free interactive maths visualisations. Brilliant for intuition.", g: ["math", "visualization", "free", "must-try"] },

  // ================================================================ Data Engineering
  { c: "Data Engineering", t: "dbt documentation (free)", u: "https://docs.getdbt.com/", d: "The free official dbt docs. The standard for data transformation.", g: ["data", "docs", "free", "must-use"] },
  { c: "Data Engineering", t: "Apache Airflow documentation", u: "https://airflow.apache.org/docs/", d: "The free official Airflow docs. Orchestration, DAGs and providers.", g: ["data", "docs", "free", "must-use"] },
  { c: "Data Engineering", t: "Apache Flink documentation", u: "https://nightlies.apache.org/flink/flink-docs-stable/", d: "The free Flink docs for stream processing at scale.", g: ["data", "streaming", "docs", "free", "must-use"] },
  { c: "Data Engineering", t: "The Data Engineering Podcast", u: "https://www.dataengineering.podcast/", d: "Free weekly podcast interviewing data engineers. Very informative.", g: ["data", "podcast", "must-follow"] },
  { c: "Data Engineering", t: "Data Is Plural (free projects)", u: "https://dataplural.net/", d: "Free guided data journalism projects. Excellent for learning by doing.", g: ["data", "projects", "free", "must-do"] },
  { c: "Data Engineering", t: "DuckDB documentation (free)", u: "https://duckdb.org/docs/", d: "Free in-process OLAP docs. Excellent for local analytics.", g: ["databases", "docs", "free", "must-use"] },
  { c: "Data Engineering", t: "Polars documentation (free)", u: "https://docs.pola.rs/", d: "Free Polars docs. Fast DataFrames in Python and Rust.", g: ["data", "docs", "free", "must-use"] },
  { c: "Data Engineering", t: "Apache Arrow documentation", u: "https://arrow.apache.org/docs/", d: "The free columnar format docs. The backbone of modern data systems.", g: ["data", "docs", "free", "must-use"] },
  { c: "Data Engineering", t: "dbt Labs blog (free)", u: "https://www.getdbt.com/blog/", d: "Free technical blog on analytics engineering. Well written.", g: ["data", "blog", "must-read"] },
  { c: "Data Engineering", t: "Vlad Mihalcea's blog", u: "https://vladmihalcea.com/", d: "Free deep blog on database performance, Hibernate and caching. Excellent.", g: ["databases", "performance", "blog", "must-read"] },
  { c: "Data Engineering", t: "The Art of PostgreSQL (free online)", u: "https://theartofpostgresql.com/", d: "A free online book on PostgreSQL internals and practice. Outstanding.", g: ["databases", "postgres", "books", "free", "must-read"] },
  { c: "Data Engineering", t: "Postgres Tips", u: "https://postgres.tips/", d: "Free practical PostgreSQL tips, mostly short and very useful.", g: ["databases", "postgres", "must-read"] },
  { c: "Data Engineering", t: "Database Internals (Alex Petrov)", u: "https://dbinternals.com/", d: "A free deep series on B-trees, LSM-trees, WAL and storage engines. Essential.", g: ["databases", "internals", "must-read", "free"] },
  { c: "Data Engineering", t: "Percona blog (free)", u: "https://www.percona.com/blog/", d: "Free deep technical blog on databases and open source. Very strong.", g: ["databases", "blog", "must-read"] },
  { c: "Data Engineering", t: "Databricks Engineering blog", u: "https://www.databricks.com/blog/category/engineering", d: "Free deep technical posts on distributed data systems. Excellent.", g: ["data", "blog", "must-read"] },
  { c: "Data Engineering", t: "PostgreSQL wiki (community)", u: "https://wiki.postgresql.org/wiki/Main_Page", d: "The free community wiki. Lots of hard-won knowledge and recipes.", g: ["databases", "postgres", "wiki", "must-use"] },
  { c: "Data Engineering", t: "Delta Lake documentation (free)", u: "https://docs.delta.io/latest/index.html", d: "Free docs for Delta Lake, the open table format. Very good.", g: ["data", "docs", "free"] },
  { c: "Data Engineering", t: "Apache Iceberg documentation", u: "https://iceberg.apache.org/docs/latest/", d: "The free docs for Apache Iceberg, the open table format.", g: ["data", "docs", "free"] },
  { c: "Data Engineering", t: "Apache Parquet documentation", u: "https://parquet.apache.org/docs/", d: "Free docs for the Parquet columnar format. Useful reference.", g: ["data", "docs", "free"] },
  { c: "Data Engineering", t: "Great Expectations docs (free)", u: "https://docs.greatexpectations.io/", d: "Free data quality framework docs. Very practical.", g: ["data", "quality", "docs", "free"] },
  { c: "Data Engineering", t: "Deequ documentation (free)", u: "https://github.com/awslabs/deequ", d: "Free open-source data quality constraints library for Spark. Very good.", g: ["data", "quality", "open-source"] },
  { c: "Data Engineering", t: "SQL style guide (free)", u: "https://www.sqlstyle.guide/", d: "The free SQL style guide. Readable SQL is a real team benefit.", g: ["sql", "style", "free", "must-read"] },
  { c: "Data Engineering", t: "OpenLineage documentation", u: "https://openlineage.io/docs/", d: "Free docs on data lineage standards. Increasingly important.", g: ["data", "docs", "free"] },

  // ================================================================ Web Performance
  { c: "Web Performance", t: "web.dev — performance guidance", u: "https://web.dev/explore/fast", d: "Free Google-authored guides on Core Web Vitals and speed. Very good.", g: ["web", "performance", "free", "must-read"] },
  { c: "Web Performance", t: "Core Web Vitals (web.dev)", u: "https://web.dev/articles/vitals", d: "The free definitive guide to LCP, INP and CLS. Must-read for perf.", g: ["web", "performance", "must-read", "free"] },
  { c: "Web Performance", t: "Chrome for Developers (free)", u: "https://developer.chrome.com/docs/devtools", d: "Free DevTools documentation. Learn the profiler properly.", g: ["web", "tooling", "docs", "free", "must-use"] },
  { c: "Web Performance", t: "Lighthouse documentation (free)", u: "https://developer.chrome.com/docs/lighthouse/overview", d: "Free Lighthouse docs. Understand the audits it reports.", g: ["web", "tooling", "docs", "free"] },
  { c: "Web Performance", t: "Web Almanac (free report)", u: "https://almanac.httparchive.org/", d: "The free annual report on the state of the web. Rich data.", g: ["web", "data", "must-read", "free"] },
  { c: "Web Performance", t: "HTTP Archive — datasets (free)", u: "https://httparchive.org/", d: "Free open datasets on real-world web performance. Very interesting.", g: ["web", "data", "open-data", "free"] },
  { c: "Web Performance", t: "MDN — Web performance (free)", u: "https://developer.mozilla.org/en-US/docs/Web/Performance", d: "Free MDN performance guides. Solid and trustworthy.", g: ["web", "performance", "free"] },
  { c: "Web Performance", t: "web.dev — learn performance", u: "https://web.dev/learn/performance", d: "Free structured learning path on web performance from Google.", g: ["web", "courses", "free"] },
  { c: "Web Performance", t: "Performance.now() conference talks (free)", u: "https://perfnow.nl/", d: "Free talks from the web performance conference. Excellent, free.", g: ["web", "performance", "video", "must-watch"] },
  { c: "Web Performance", t: "Chrome UX Report API docs (free)", u: "https://developer.chrome.com/docs/crux/api", d: "Free docs for field performance data on real users. Very advanced.", g: ["web", "performance", "docs", "free"] },
  { c: "Web Performance", t: "INP — Interaction to Next Paint (free)", u: "https://web.dev/articles/inp", d: "The free deep guide to INP, the responsiveness metric. Must-read.", g: ["web", "performance", "must-read", "free"] },
  { c: "Web Performance", t: "HTTP caching (MDN, free)", u: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching", d: "Free MDN guide on HTTP caching. A high-leverage perf topic.", g: ["web", "http", "free", "must-read"] },
  { c: "Web Performance", t: "Smashing Magazine (free)", u: "https://www.smashingmagazine.com/", d: "Free long-form web articles on performance, design and accessibility.", g: ["web", "must-read", "free"] },

  // ================================================================ Self-taught learning
  { c: "Self-taught learning", t: "Eloquent JavaScript (free book)", u: "https://eloquentjavascript.net/", d: "A free, excellent JavaScript book that teaches the language properly.", g: ["javascript", "books", "free", "must-read"] },
  { c: "Self-taught learning", t: "javascript.info (free)", u: "https://javascript.info/", d: "The free best-structured JavaScript tutorial on the web. Outstanding.", g: ["javascript", "tutorial", "free", "must-do"] },
  { c: "Self-taught learning", t: "You Don't Know JS (free)", u: "https://github.com/getify/You-Dont-Know-JS", d: "Free in-depth books on JavaScript mechanics. Deep and rigorous.", g: ["javascript", "books", "free", "must-read"] },
  { c: "Self-taught learning", t: "Automate the Boring Stuff with Python (free)", u: "https://automatetheboringstuff.com/", d: "A free complete Python book for absolute beginners. Very practical.", g: ["python", "books", "free", "beginner", "must-do"] },
  { c: "Self-taught learning", t: "Think Python (free)", u: "https://greenteapress.com/wp/think-python/", d: "Downey's free Python book that teaches computing as well as Python.", g: ["python", "books", "free", "must-read"] },
  { c: "Self-taught learning", t: "Dive into Python 3 (free)", u: "https://diveintopython3.problemsolving.io/", d: "A free in-depth Python book. Good for understanding the why.", g: ["python", "books", "free"] },
  { c: "Self-taught learning", t: "Learn You Some Erlang for Great Good (free)", u: "http://learnyoualittlemorerest.com/", d: "A free fun introduction to Erlang and OTP. Very good for concurrency.", g: ["erlang", "functional", "books", "free", "must-do"] },
  { c: "Self-taught learning", t: "Clojure for the Brave and True (free)", u: "https://www.braveclojure.com/", d: "A free excellent Clojure book covering both basics and real practice.", g: ["clojure", "books", "free", "must-read"] },
  { c: "Self-taught learning", t: "Real World OCaml (free book)", u: "https://realworldocaml.org/", d: "A free book on practical OCaml. Very well written.", g: ["ocaml", "books", "free", "must-read"] },
  { c: "Self-taught learning", t: "Haskell School of Expression (free)", u: "http://haskell.galois.com/", d: "A free intro to Haskell as a functional language, with graphics.", g: ["haskell", "books", "free"] },
  { c: "Self-taught learning", t: "Problem Solving with Algorithms and Data Structures (free)", u: "https://runestone.academy/nspe/p/index.html", d: "A free Python textbook on algorithms and data structures. Excellent.", g: ["python", "algorithms", "books", "free", "must-do"] },
  { c: "Self-taught learning", t: "MIT Rust course (free)", u: "https://rust-class.github.io/", d: "A free MIT-style Rust course. Very practical and well structured.", g: ["rust", "courses", "free", "must-do"] },

  // ================================================================ Tech Pioneers
  { c: "Tech pioneers", t: "Bret Victor — Worry Dream", u: "https://worrydream.com/", d: "Bret Victor's writing on computing, tools and education. Highly original.", g: ["blog", "must-read", "vision"] },
  { c: "Tech pioneers", t: "Jef Raskin — Motherfucking Software", u: "https://motherfuckingsoftware.com/", d: "Jef Raskin's free manifestos on software and design. Hilarious and profound.", g: ["blog", "must-read", "design"] },
  { c: "Tech pioneers", t: "Jaron Lanier", u: "https://www.jaronlanier.com/", d: "Free writing on virtual reality, digital rights and the future. Influential.", g: ["blog", "society", "must-read"] },
  { c: "Tech pioneers", t: "Sam Altman's blog", u: "https://blog.samaltman.com/", d: "Free writing on AI, startups and what comes next. Very well argued.", g: ["blog", "ai", "must-read"] },
  { c: "Tech pioneers", t: "Tim Bray's Ongoing", u: "https://www.tbray.org/ongoing/", d: "The co-inventor of XML on Java, HTTP and the web. Outstanding writer.", g: ["blog", "must-read", "web"] },
  { c: "Tech pioneers", t: "Philip Greenspun's blog", u: "https://pgbovine.net/", d: "Free essays on software, the web and startups from a veteran. Sharp.", g: ["blog", "must-read"] },
  { c: "Tech pioneers", t: "Eric Sink — Sink of the Border", u: "https://www.ericsink.com/", d: "Free blog on version control, tools and developer productivity. Excellent.", g: ["blog", "git", "must-read"] },
  { c: "Tech pioneers", t: "Raymond Chen — Old New Thing", u: "https://devblogs.microsoft.com/oldnewthing/", d: "Free posts explaining Windows internals and how it all actually works.", g: ["blog", "windows", "must-read"] },
  { c: "Tech pioneers", t: "Russ Cox's blog", u: "https://swtch.com/~rsc/", d: "The Go creator's free blog on concurrency, C and systems. Essential.", g: ["blog", "go", "must-read"] },
  { c: "Tech pioneers", t: "Pavel Panchekha's blog", u: "https://blog.pavel.pw/", d: "Free blog on Go, Go internals, hardware and language design. Very strong.", g: ["blog", "go", "must-read"] },
  { c: "Tech pioneers", t: "Michael Munday's blog", u: "https://mmunday.com/", d: "Free blog on compilers, language design and research papers. Deep.", g: ["blog", "compilers", "must-read"] },
  { c: "Tech pioneers", t: "Hans Boehm's blog", u: "https://hboehm.info/", d: "Free writing on garbage collection, compilers and language design. Rigorous.", g: ["blog", "compilers", "gc", "must-read"] },
  { c: "Tech pioneers", t: "Guy L. Steele's page", u: "https://people.csail.mit.edu/guy/", d: "Common Lisp and Scheme co-designer. Free papers, talks and writings.", g: ["lisp", "history", "must-read"] },
  { c: "Tech pioneers", t: "John McCarthy's papers (free)", u: "https://www-formal.stanford.edu/jmc/", d: "The original AI papers and essays, free. A primary source.", g: ["ai", "history", "must-read", "free"] },
  { c: "Tech pioneers", t: "Douglas Hofstadter's site", u: "https://www.douglas-hofstadter.com/", d: "Gödel, Escher, Bach and Hofstadter's laws. Free writing on mind and computation.", g: ["blog", "must-read", "cognitive-science"] },
  { c: "Tech pioneers", t: "Tim O'Reilly's Radar", u: "https://www.oreilly.com/radar/", d: "Free essays on software and technology trends from O'Reilly's founder.", g: ["blog", "industry", "must-read"] },
  { c: "Tech pioneers", t: "Ted Nelson — Hypertext", u: "https://www.hypertext.org/", d: "The inventor of hypertext on his own work. Primary source, free.", g: ["history", "free", "must-read"] },
  { c: "Tech pioneers", t: "Ron Jeffries' blog", u: "https://ronjeffries.com/", d: "xUnit and Extreme Programming. Free writing on agile and TDD. Influential.", g: ["blog", "tdd", "must-read"] },
  { c: "Tech pioneers", t: "Dave Thomas (Pragmatic Programmer)", u: "https://pragprog.com/", d: "The Pragmatic Programmer's site. Free articles on software craftsmanship.", g: ["blog", "process", "must-read"] },
  { c: "Tech pioneers", t: "Joe Armstrong — Erlang", u: "https://www.erlang.org/blog/", d: "The Erlang creator's free blog on concurrency and functional programming.", g: ["erlang", "blog", "must-read"] },
  { c: "Tech pioneers", t: "Alan Kay's page", u: "https://www.alan-kay.com/", d: "The Dynabook and OOP visionary's free page and writings.", g: ["history", "vision", "must-read"] },
  { c: "Tech pioneers", t: "Chuck Peddle — the 6502 story", u: "https://www.pagetable.com/", d: "Free Commodore 64 and 6502 reverse engineering. Legendary resource.", g: ["history", "hardware", "must-visit"] },
  { c: "Tech pioneers", t: "The Digital Antiquarian (free essays)", u: "https://www.filfre.net/", d: "Free, beautifully written essays on the history of computer games.", g: ["history", "free", "must-read"] },
  { c: "Tech pioneers", t: "Retrocomputing Stack Exchange (free)", u: "https://retrocomputing.stackexchange.com/", d: "Free Q&A on old hardware and software. Deep and friendly.", g: ["history", "community", "free"] },
  { c: "Tech pioneers", t: "Adam Back — hashcash (free)", u: "https://www.hashcash.org/", d: "Free explanation of hashcash, the proof-of-work idea behind Bitcoin.", g: ["crypto", "history", "free"] },
  { c: "Tech pioneers", t: "Hal Finney — reusable proof of work (free)", u: "https://www.reusableproofofwork.com/", d: "Free early Bitcoin design documents. A fascinating primary source.", g: ["crypto", "history", "free"] },
  { c: "Tech pioneers", t: "Plan 9 from Bell Labs (free)", u: "https://plan9.io/", d: "Free documentation and papers from Bell Labs' Plan 9 OS. Very deep.", g: ["history", "systems", "free", "must-read"] },
  { c: "Tech pioneers", t: "Inferno — Plan 9 virtual machine (free)", u: "https://vitanuova.com/inferno/", d: "Free docs for Inferno, the Plan 9 successor. Fascinating design.", g: ["history", "systems", "free"] },
  { c: "Tech pioneers", t: "The Bitcoin whitepaper (free)", u: "https://bitcoin.org/bitcoin.pdf", d: "The free primary source. Nine pages that changed the world.", g: ["crypto", "must-read", "free"] },
  { c: "Tech pioneers", t: "Ethereum whitepaper (free)", u: "https://ethereum.org/en/whitepaper/", d: "The free primary source for Ethereum's design.", g: ["crypto", "must-read", "free"] },
  { c: "Tech pioneers", t: "Turing's paper — computing machinery (free)", u: "https://academic.oup.com/mind/article/LIX/236/433/986680", d: "The free primary source on computability. A landmark paper.", g: ["theory", "history", "must-read"] },
];
