// Part 4: Artificial intelligence, ML, LLMs
const BOOKMARKS_04 = [
  { c: "AI / ML", t: "Hugging Face — the hub", u: "https://huggingface.co/", d: "Models, datasets, Spaces and docs. The center of open ML.", g: ["ai", "ml", "hub", "must-know"] },
  { c: "AI / ML", t: "Hugging Face — Daily Papers", u: "https://huggingface.co/papers", d: "The best ML paper feed, with community explanations. Daily.", g: ["ai", "papers", "must-read"] },
  { c: "AI / ML", t: "Hugging Face — Learn (free courses)", u: "https://huggingface.co/learn", d: "Free courses: NLP, deep RL, audio, CV, LLM course, agents. Excellent.", g: ["ai", "free-course", "must-do"] },
  { c: "AI / ML", t: "Hugging Face — LLM Course", u: "https://huggingface.co/learn/llm-course", d: "Free course: APIs, RAG, agents, fine-tuning, quantization.", g: ["ai", "llm", "free-course"] },
  { c: "AI / ML", t: "Hugging Face — smol-course", u: "https://huggingface.co/learn/smol-course", d: "Tiny hands-on course to fine-tune and use open LLMs. Beginner friendly.", g: ["ai", "free-course", "llm"] },
  { c: "AI / ML", t: "Hugging Face — Transformers docs", u: "https://huggingface.co/docs/transformers/", d: "The best practical library docs in ML. Learn from the notebooks.", g: ["ai", "ml", "docs"] },
  { c: "AI / ML", t: "fast.ai — Practical Deep Learning", u: "https://course.fast.ai/", d: "Top-down, free, project-based deep learning. Best intro if you build.", g: ["ai", "free-course", "deep-learning"] },
  { c: "AI / ML", t: "OpenAI Spinning Up", u: "https://spinningup.openai.com/", d: "Free rigorous RL primer (DQN, PPO, SAC). Still the best RL tutorial.", g: ["ai", "rl", "free-course"] },
  { c: "AI / ML", t: "DeepLearning.AI short courses", u: "https://www.deeplearning.ai/short-courses/", d: "Free 1-2 hour courses on agents, LangChain, transformers, RAG.", g: ["ai", "free-course", "llm"] },
  { c: "AI / ML", t: "Anthropic — Research", u: "https://www.anthropic.com/research", d: "Constitutional AI, interpretability, RLHF, evaluations. Read the papers.", g: ["ai", "papers", "llm"] },
  { c: "AI / ML", t: "Anthropic — Engineering blog", u: "https://www.anthropic.com/engineering", d: "How they actually build Claude: agents, evals, systems, safety.", g: ["ai", "blog", "llm", "must-read"] },
  { c: "AI / ML", t: "Building Effective Agents (Anthropic)", u: "https://www.anthropic.com/engineering/building-effective-agents", d: "The clearest free explanation of workflows vs agents. Read this.", g: ["ai", "agents", "must-read"] },
  { c: "AI / ML", t: "Anthropic Docs (API)", u: "https://docs.anthropic.com/", d: "API reference, prompt engineering guide, tool-use and MCP docs.", g: ["ai", "llm", "api"] },
  { c: "AI / ML", t: "Anthropic prompt engineering guide", u: "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview", d: "Practical prompting: XML tags, examples, chaining. Very actionable.", g: ["ai", "prompting", "must-read"] },
  { c: "AI / ML", t: "OpenAI Research", u: "https://openai.com/research/", d: "Research index: GPT, alignment, o-series, and more.", g: ["ai", "papers", "llm"] },
  { c: "AI / ML", t: "OpenAI Cookbook", u: "https://cookbook.openai.com/", d: "Practical recipes for prompting, RAG, tools, evals. Free.", g: ["ai", "llm", "recipes"] },
  { c: "AI / ML", t: "DeepMind blog", u: "https://deepmind.google/discover/blog/", d: "AlphaFold, Gemini, agents. Accessible write-ups of frontier work.", g: ["ai", "blog"] },
  { c: "AI / ML", t: "Google AI blog", u: "https://blog.google/technology/ai/", d: "Google and DeepMind product and research announcements.", g: ["ai", "blog"] },
  { c: "AI / ML", t: "BAIR Blog (Berkeley AI Research)", u: "https://bair.berkeley.edu/blog/", d: "Research summaries from Berkeley's AI lab. Strong on RL and vision.", g: ["ai", "blog", "research"] },
  { c: "AI / ML", t: "Meta AI blog", u: "https://ai.meta.com/blog/", d: "Llama, SAM and FAIR research write-ups.", g: ["ai", "blog", "llm"] },
  { c: "AI / ML", t: "Microsoft Research Blog", u: "https://www.microsoft.com/en-us/research/blog/", d: "Deep technical posts on models, systems and responsible AI.", g: ["ai", "blog", "research"] },
  { c: "AI / ML", t: "Mistral AI news", u: "https://mistral.ai/news/", d: "Open-weight models and technical notes. Read the open releases.", g: ["ai", "llm", "open-weights"] },
  { c: "AI / ML", t: "Qwen (Alibaba) models & blog", u: "https://qwenlm.github.io/", d: "Strong open-weight models with good releases and blog posts.", g: ["ai", "llm", "open-weights"] },
  { c: "AI / ML", t: "arXiv cs.LG recent", u: "https://arxiv.org/list/cs.LG/recent", d: "The ML firehose. Filter via HF Papers when you can.", g: ["ai", "papers"] },
  { c: "AI / ML", t: "arXiv cs.AI recent", u: "https://arxiv.org/list/cs.AI/recent", d: "The AI subset of arXiv.", g: ["ai", "papers"] },
  { c: "AI / ML", t: "arXiv cs.CL recent (NLP/LLM)", u: "https://arxiv.org/list/cs.CL/recent", d: "Computational linguistics and LLM papers.", g: ["ai", "papers", "nlp"] },
  { c: "AI / ML", t: "ar5iv (arXiv to HTML)", u: "https://ar5iv.labs.arxiv.org/", d: "Renders arXiv papers as readable HTML with proper equations.", g: ["ai", "papers", "reading"] },
  { c: "AI / ML", t: "Papers with Code", u: "https://paperswithcode.com/", d: "Papers linked to runnable code and leaderboards. Winding down but useful archive.", g: ["ai", "papers"] },
  { c: "AI / ML", t: "Distill", u: "https://distill.pub/", d: "Interactive, beautifully explained ML ideas. A gold standard explainer.", g: ["ai", "explainer", "must-read"] },
  { c: "AI / ML", t: "The Gradient", u: "https://thegradient.pub/", d: "Narrative essays on the science and philosophy of machine learning.", g: ["ai", "essay"] },
  { c: "AI / ML", t: "Latent Space podcast", u: "https://www.latent.space/", d: "The best AI-engineering podcast: infra, evals, agents, interviews.", g: ["ai", "podcast", "must-follow"] },
  { c: "AI / ML", t: "Interconnections (One Useful Thing)", u: "https://www.interconnections.ai/", d: "Ethan Mollick on how to actually use LLMs effectively.", g: ["ai", "practical", "must-read"] },
  { c: "AI / ML", t: "Import AI (Jack Clark)", u: "https://importai.substack.com/", d: "Weekly synthesis of AI research, policy and compute. Sharp.", g: ["ai", "newsletter"] },
  { c: "AI / ML", t: "Simon Willison's Weblog (LLM tags)", u: "https://simonwillison.net/tags/llms/", d: "Daily notes on LLMs, RAG, agents and building with them. Superb.", g: ["ai", "blog", "must-read"] },
  { c: "AI / ML", t: "Karpathy — A Recipe for Neural Networks", u: "https://karpathy.ai/2019/04/25/recipe/", d: "Building a neural net in pure Python, explained. Gold.", g: ["ai", "neural-nets", "must-read"] },
{ c: "AI / ML", t: "Karpathy's Zero to Hero course", u: "https://karpathy.ai/zero-to-hero.html", d: "Free, complete neural-network course: from backprop to GPT. Start here.", g: ["ai", "llm", "code"] },
  { c: "AI / ML", t: "nanoGPT (Karpathy)", u: "https://github.com/karpathy/nanoGPT", d: "GPT in ~300 lines. Read the code to demystify transformers.", g: ["ai", "llm", "code", "must-read"] },
  { c: "AI / ML", t: "llm.c (Karpathy)", u: "https://github.com/karpathy/llm.c", d: "LLM training in raw C. See what frameworks hide from you.", g: ["ai", "llm", "c", "advanced"] },
  { c: "AI / ML", t: "The Illustrated Transformer", u: "https://jalammar.github.io/illustrated-transformer/", d: "The clearest visual explanation of attention and transformers.", g: ["ai", "explainer", "must-read"] },
  { c: "AI / ML", t: "The Illustrated GPT-2", u: "https://jalammar.github.io/illustrated-gpt2/", d: "How a real LM processes text, step by step. Excellent.", g: ["ai", "explainer"] },
  { c: "AI / ML", t: "The Illustrated Stable Diffusion", u: "https://jalammar.github.io/illustrated-stable-diffusion/", d: "Clear visual explanation of diffusion models. Great intro.", g: ["ai", "explainer", "diffusion"] },
  { c: "AI / ML", t: "Reinforcement Learning: An Introduction", u: "https://rlbook.mit.edu/", d: "Sutton & Barto's definitive free RL textbook, 2nd edition.", g: ["ai", "rl", "book", "must-read"] },
  { c: "AI / ML", t: "Stanford CS224n (NLP)", u: "https://web.stanford.edu/class/cs224n/", d: "Free NLP course materials: slides, code, videos.", g: ["ai", "nlp", "free-course"] },
  { c: "AI / ML", t: "Stanford CS231n (vision)", u: "https://cs231n.github.io/", d: "Free, excellent deep learning for computer vision with assignments.", g: ["ai", "computer-vision", "free-course"] },
  { c: "AI / ML", t: "Berkeley CS285 (deep RL)", u: "https://rail.eecs.berkeley.edu/deeprlcourse/", d: "Free advanced deep RL course. Assignments implement real algorithms.", g: ["ai", "rl", "free-course"] },
  { c: "AI / ML", t: "Berkeley LLM Agents course (Gorilla)", u: "https://github.com/ShishirPatil/gorilla", d: "The Berkeley LLM agents course. Free, current and practical.", g: ["ai", "agents", "free-course", "must-do"] },
  { c: "AI / ML", t: "Ollama — run LLMs locally", u: "https://ollama.com/", d: "One-command local LLMs. Best on-ramp to running models yourself.", g: ["ai", "llm", "local", "must-try"] },
  { c: "AI / ML", t: "LM Studio", u: "https://lmstudio.ai/", d: "Friendly GUI for local models, with a local HTTP API. Great for tinkering.", g: ["ai", "llm", "local"] },
  { c: "AI / ML", t: "llama.cpp", u: "https://github.com/ggml-org/llama.cpp", d: "Run quantized LLMs on CPU/laptop. Popular and fast.", g: ["ai", "llm", "local", "cpp"] },
  { c: "AI / ML", t: "vLLM", u: "https://github.com/vllm-project/vllm", d: "High-throughput LLM serving. Learn from its optimization write-ups.", g: ["ai", "infra", "serving"] },
  { c: "AI / ML", t: "LangChain", u: "https://www.langchain.com/", d: "The most common LLM app framework. Learn the primitives, then the abstractions.", g: ["ai", "llm", "framework"] },
  { c: "AI / ML", t: "LlamaIndex", u: "https://www.llamaindex.ai/", d: "Data framework for connecting LLMs to your documents. Great RAG docs.", g: ["ai", "llm", "rag"] },
  { c: "AI / ML", t: "Modal blog (AI infra)", u: "https://modal.com/blog", d: "Practical GPU and AI infra: serving, batching, cold starts.", g: ["ai", "infra", "blog"] },
  { c: "AI / ML", t: "Replicate blog", u: "https://replicate.com/blog", d: "Open model demos and how they serve models at scale.", g: ["ai", "infra", "blog"] },
  { c: "AI / ML", t: "Together AI blog", u: "https://www.together.ai/blog", d: "Open models, fine-tuning and inference optimization write-ups.", g: ["ai", "blog", "llm"] },
  { c: "AI / ML", t: "Groq blog", u: "https://groq.com/blog", d: "Fast LLM inference on custom hardware. Good performance engineering.", g: ["ai", "infra", "performance"] },
  { c: "AI / ML", t: "Cohere for AI blog", u: "https://cohere.com/blog", d: "Technically strong posts on embeddings, RAG and evaluation.", g: ["ai", "rag", "blog"] },
  { c: "AI / ML", t: "OWASP Top 10 for LLM Applications", u: "https://owasp.org/www-project-top-10-for-large-language-model-applications/", d: "Prompt injection, RAG poisoning and other LLM app security risks.", g: ["ai", "security", "must-know"] },
  { c: "AI / ML", t: "EleutherAI", u: "https://www.eleuther.ai/", d: "Open, non-profit GPT research collective behind The Pile.", g: ["ai", "research"] },
  { c: "AI / ML", t: "Stanford AI Index Report", u: "https://aiindex.stanford.edu/report/", d: "Annual state of AI: benchmarks, costs, incidents. Free report.", g: ["ai", "report", "data"] },
  { c: "AI / ML", t: "Our World in Data — AI", u: "https://ourworldindata.org/artificial-intelligence", d: "Data-driven visuals on AI progress and impact. Great for intuition.", g: ["ai", "data", "visuals"] },
  { c: "AI / ML", t: "MCP documentation (Model Context Protocol)", u: "https://modelcontextprotocol.io/", d: "The open protocol for connecting LLMs to tools and data. Learn it early.", g: ["ai", "agents", "tooling", "must-know"] },
  { c: "AI / ML", t: "MCP servers directory", u: "https://github.com/modelcontextprotocol/servers", d: "Reference MCP server implementations to learn from.", g: ["ai", "agents", "code"] },
  { c: "AI / ML", t: "OpenAI Realtime / agents guides", u: "https://platform.openai.com/docs/guides", d: "API guides for building agents, tools and realtime features.", g: ["ai", "api", "agents"] },
  { c: "AI / ML", t: "Gradio — build AI demos fast", u: "https://www.gradio.app/", d: "The standard way to ship an AI demo UI. Free and open source.", g: ["ai", "tooling", "ui"] },
  { c: "AI / ML", t: "Streamlit — data/AI apps", u: "https://streamlit.io/", d: "Turn a Python script into a shareable app. Free and open source.", g: ["ai", "tooling", "ui"] },
  { c: "AI / ML", t: "Weights & Biases docs (free tier)", u: "https://docs.wandb.ai/", d: "Experiment tracking, sweeps and model registry. Good free tier.", g: ["ai", "tooling", "mlops"] },
  { c: "AI / ML", t: "MLflow", u: "https://mlflow.org/", d: "Open-source experiment tracking and model lifecycle management.", g: ["ai", "mlops", "open-source"] },
  { c: "AI / ML", t: "JAX documentation", u: "https://docs.jax.dev/", d: "Composable transformations for ML. Learn if you need custom accelerators.", g: ["ai", "ml", "framework"] },
  { c: "AI / ML", t: "NumPy / numerical computing docs", u: "https://numpy.org/doc/stable/", d: "The foundation of most Python ML. Reading these helps you write faster code.", g: ["ml", "python", "reference"] },
  { c: "AI / ML", t: "scikit-learn user guide", u: "https://scikit-learn.org/stable/user_guide.html", d: "The classic ML algorithms with clear, practical examples.", g: ["ml", "python", "must-read"] },
  { c: "AI / ML", t: "PyTorch tutorials", u: "https://docs.pytorch.org/tutorials/", d: "The main PyTorch learning path. Start with the 60-minute basics.", g: ["ai", "ml", "pytorch", "tutorial"] },
  { c: "AI / ML", t: "Google PAIR — People + AI Research", u: "https://pair.withgoogle.com/", d: "Human-centered AI design, explainers and toolkits. Great for product AI.", g: ["ai", "ux", "product"] },
  { c: "AI / ML", t: "Kagi / independent AI search", u: "https://blog.kagi.com/", d: "Kagi's blog posts on building a search engine with LLM reranking.", g: ["ai", "search", "blog"] },
  { c: "AI / ML", t: "Aider — AI pair programming in terminal", u: "https://aider.chat/", d: "Open-source AI coding assistant you run yourself. Great for experiments.", g: ["ai", "tooling", "coding"] },
  { c: "AI / ML", t: "Prompt Engineering Guide (DAIR.AI)", u: "https://www.promptingguide.ai/", d: "A free, well-organized guide to prompting techniques and papers.", g: ["ai", "prompting", "reference"] },
  { c: "AI / ML", t: "Gemma / open models on HF", u: "https://huggingface.co/google", d: "Google's open models, plus strong fine-tuned variants from the community.", g: ["ai", "open-weights", "llm"] }
];
