// Part 2: Go language, Go frameworks, Go blogs
const BOOKMARKS_02 = [
  { c: "Go", t: "The Go Programming Language", u: "https://go.dev/", d: "Home base: docs, blog, releases, package index.", g: ["go", "official"] },
  { c: "Go", t: "A Tour of Go", u: "https://go.dev/tour/", d: "The official interactive tutorial. Do it once, start to finish.", g: ["go", "tutorial", "must-do"] },
  { c: "Go", t: "Effective Go", u: "https://go.dev/doc/effective_go", d: "The idiomatic-Go essay. Short and essential.", g: ["go", "must-read"] },
  { c: "Go", t: "The Go Language Specification", u: "https://go.dev/ref/spec", d: "The actual language contract. Reference, not bedtime reading.", g: ["go", "spec", "reference"] },
  { c: "Go", t: "Go by Example", u: "https://gobyexample.com/", d: "Annotated example code. Best way to get quick syntax fluency.", g: ["go", "tutorial", "examples"] },
  { c: "Go", t: "Go Proverbs", u: "https://go-proverbs.github.io/", d: "Write straight code; clear beats clever; don't fear small interfaces.", g: ["go", "style", "short"] },
  { c: "Go", t: "Go Code Review Comments", u: "https://go.dev/wiki/CodeReviewComments", d: "The de-facto style + design review checklist.", g: ["go", "style", "review"] },
  { c: "Go", t: "The official Go Wiki", u: "https://github.com/golang/go/wiki", d: "Community wiki: best practices, error handling, concurrency, FAQ.", g: ["go", "wiki"] },
  { c: "Go", t: "Go Blog", u: "https://go.dev/blog/", d: "Release notes, design rationale, proposals, and the annual survey.", g: ["go", "blog", "official"] },
  { c: "Go", t: "pkg.go.dev", u: "https://pkg.go.dev/", d: "The canonical module and package documentation browser.", g: ["go", "docs", "reference"] },
  { c: "Go", t: "Go Time (Changelog podcast)", u: "https://changelog.com/gotime", d: "The best regular Go podcast. Deep interviews with the core team.", g: ["go", "podcast", "must-follow"] },
  { c: "Go", t: "Go Weekly newsletter", u: "https://golangweekly.com/", d: "Weekly curated Go links. Low noise, high signal.", g: ["go", "newsletter"] },
  { c: "Go", t: "Go Lab (Delve, pprof, stats)", u: "https://go-lab.io/", d: "Jonathan Amsterdam's deep dives on Go tooling, tracing and debugging.", g: ["go", "profiling", "tooling"] },
  { c: "Go", t: "Structured logging with log/slog", u: "https://go.dev/blog/slog", d: "The stdlib structured logger; design article explains the choices.", g: ["go", "logging"] },
  { c: "Go", t: "Go pipelines (concurrency)", u: "https://go.dev/blog/pipelines", d: "The practical pipelines pattern with a clear walkthrough.", g: ["go", "concurrency"] },
  { c: "Go", t: "golang.org/x/sync/errgroup", u: "https://pkg.go.dev/golang.org/x/sync/errgroup", d: "The idiomatic bounded-parallelism tool. Read the examples.", g: ["go", "concurrency", "must-know"] },
  { c: "Go", t: "Go error handling guide", u: "https://go.dev/blog/error-handling-and-go", d: "How the Go team thinks about errors. Great design discussion.", g: ["go", "errors", "must-read"] },
  { c: "Go", t: "Context in Go (official blog)", u: "https://go.dev/blog/context", d: "Why context.Context exists and how to use it correctly.", g: ["go", "concurrency", "must-read"] },
  { c: "Go", t: "Go generics tutorial", u: "https://go.dev/doc/tutorial/generics", d: "The official generics tutorial, with type parameters explained.", g: ["go", "generics"] },
  { c: "Go", t: "Go memory model", u: "https://go.dev/ref/mem", d: "The rules for memory visibility across goroutines. Read once, understand forever.", g: ["go", "concurrency", "reference"] },
  { c: "Go", t: "Go talks conference", u: "https://go.dev/talks/", d: "Official conference talks, all with slides and video.", g: ["go", "video", "talks"] },
  { c: "Go", t: "Go fuzzing tutorial", u: "https://go.dev/doc/tutorial/fuzz", d: "Native Go fuzzing. Practical way to harden parsers.", g: ["go", "testing", "security"] },
  { c: "Go", t: "Go profiling docs (pprof)", u: "https://pkg.go.dev/net/http/pprof", d: "Go's built-in profiling endpoint. Learn before you optimize.", g: ["go", "profiling", "must-know"] },
  { c: "Go", t: "Delve debugger", u: "https://github.com/go-delve/delve", d: "The Go debugger with DAP support for editors. The go-to debug tool.", g: ["go", "debugging", "tooling"] },

  { c: "Go frameworks", t: "chi — lightweight router", u: "https://github.com/go-chi/chi", d: "net/http-native router used by countless APIs. Tiny and composable.", g: ["go", "http", "router"] },
  { c: "Go frameworks", t: "Gin", u: "https://github.com/gin-gonic/gin", d: "The most popular full-featured Go web framework. Huge ecosystem.", g: ["go", "http", "web-framework"] },
  { c: "Go frameworks", t: "Echo", u: "https://github.com/labstack/echo", d: "Minimal, extensible, fast Go web framework.", g: ["go", "http", "web-framework"] },
  { c: "Go frameworks", t: "Fiber", u: "https://github.com/gofiber/fiber", d: "Express-inspired API on fasthttp. Very fast, opinionated.", g: ["go", "http", "web-framework"] },
  { c: "Go frameworks", t: "go-zero (microservices)", u: "https://github.com/zeromicro/go-zero", d: "Kitex + goctl: batteries-included microservice framework.", g: ["go", "microservices"] },
  { c: "Go frameworks", t: "Kratos (microservices)", u: "https://go-kratos.dev/", d: "Bilibili-origin microservices framework with proto-first clean layout.", g: ["go", "microservices", "ddd"] },
  { c: "Go frameworks", t: "go-micro", u: "https://github.com/go-micro/go-micro", d: "Plugin-based microservice framework. Long-running, very active.", g: ["go", "microservices"] },
  { c: "Go frameworks", t: "Watermill (event-driven)", u: "https://watermill.io/", d: "Library for building event-driven apps: pub/sub, queues, streaming.", g: ["go", "messaging", "eda"] },
  { c: "Go frameworks", t: "go-kit", u: "https://gokit.io/", d: "Deliberately minimal toolkit: transport, logging, metrics, tracing.", g: ["go", "microservices"] },
  { c: "Go frameworks", t: "Buffalo", u: "https://gobuffalo.io/", d: "Classic Go web framework with generators, migrations, job queue.", g: ["go", "web-framework"] },
  { c: "Go frameworks", t: "Ogen (OpenAPI codegen)", u: "https://ogen.dev/", d: "OpenAPI v3 generator with zero reflection; very fast generated servers.", g: ["go", "openapi", "codegen"] },
  { c: "Go frameworks", t: "ent — entity framework", u: "https://entgo.io/", d: "Graph-based schema/ORM for Go; code generation, no reflection.", g: ["go", "orm", "database"] },
  { c: "Go frameworks", t: "GORM", u: "https://gorm.io/", d: "The most popular Go ORM. Great migrations, plugins, associations.", g: ["go", "orm", "database"] },
  { c: "Go frameworks", t: "sqlc — generate Go from SQL", u: "https://sqlc.dev/", d: "Write SQL, get type-safe Go. The sweet spot between raw SQL and ORM.", g: ["go", "sql", "codegen", "must-know"] },
  { c: "Go frameworks", t: "Bun ORM", u: "https://bun.uptrace.dev/", d: "Modern composable ORM with good PostgreSQL-first ergonomics.", g: ["go", "orm"] },
  { c: "Go frameworks", t: "Atlas — schema migrations", u: "https://atlasgo.io/", d: "Declarative migrations for SQL databases. Works with ent or plain SQL.", g: ["go", "migrations", "database"] },
  { c: "Go frameworks", t: "golangci-lint", u: "https://golangci-lint.run/", d: "The de-facto linter aggregator for Go (30+ linters in one run).", g: ["go", "linting", "ci", "must-have"] },
  { c: "Go frameworks", t: "staticcheck", u: "https://staticcheck.dev/", d: "The most thoughtful static analyzer for Go. Run it in CI.", g: ["go", "linting", "must-know"] },
  { c: "Go frameworks", t: "gofumpt", u: "https://mvdan.cc/gofumpt/", d: "Stricter gofmt. The formatter most Go teams actually use.", g: ["go", "formatting", "tooling"] },
  { c: "Go frameworks", t: "gopls language server", u: "https://pkg.go.dev/golang.org/x/tools/gopls", d: "The official Go language server powering editor intelligence.", g: ["go", "tooling"] },
  { c: "Go frameworks", t: "Cobra + Viper (CLI apps)", u: "https://github.com/spf13/cobra", d: "The most popular CLI framework. Viper for config. Used by k9s, hugo.", g: ["go", "cli", "tooling"] },
  { c: "Go frameworks", t: "Taskfile (Task)", u: "https://taskfile.dev/", d: "A Make alternative with better ergonomics, YAML, and includes.", g: ["go", "tooling", "build"] },
  { c: "Go frameworks", t: "air — live reload", u: "https://github.com/air-verse/air", d: "Live reload for Go web dev. Big QoL win for the inner loop.", g: ["go", "dx", "tooling"] },
  { c: "Go frameworks", t: "mockery", u: "https://vektra.github.io/mockery/", d: "Generates testify mocks from interfaces. Common in Go test suites.", g: ["go", "testing", "mocking"] },
  { c: "Go frameworks", t: "go.uber.org/mock (gomock)", u: "https://github.com/uber-go/mock", d: "The maintained fork of gomock. Standard for interface mocks.", g: ["go", "testing", "mocking"] },
  { c: "Go frameworks", t: "testify", u: "https://github.com/stretchr/testify", d: "The ubiquitous assertion/mock/suite library for Go tests.", g: ["go", "testing"] },
  { c: "Go frameworks", t: "testcontainers-go", u: "https://golang.testcontainers.org/", d: "Spin up Postgres/Redis/etc. in Docker for integration tests.", g: ["go", "testing", "integration"] },
  { c: "Go frameworks", t: "CUE (configuration language)", u: "https://cuelang.org/", d: "Google's language for defining data & constraints. Config validation.", g: ["go", "config"] },
  { c: "Go frameworks", t: "Templ (typed HTML templates)", u: "https://templ.guide/", d: "Type-safe, compile-checked HTML templates with great DX.", g: ["go", "templates", "web"] },
  { c: "Go frameworks", t: "Litestream", u: "https://litestream.io/", d: "Continuous SQLite replication to S3. Amazing for small/edge apps.", g: ["go", "sqlite", "database"] },
  { c: "Go frameworks", t: "PocketBase", u: "https://pocketbase.io/", d: "Single-file Go backend: auth, DB, realtime, admin UI. Great for MVPs.", g: ["go", "backend", "tooling"] },
  { c: "Go frameworks", t: "Dagger (CI/CD in Go)", u: "https://dagger.io/", d: "CI/CD pipelines as Go code with a deterministic engine. Very cool.", g: ["go", "cicd", "devops"] },
  { c: "Go frameworks", t: "Kong CLI parser", u: "https://github.com/alecthomas/kong", d: "Modern minimal struct-tag CLI parser. Great DX for Go CLIs.", g: ["go", "cli"] },
  { c: "Go frameworks", t: "Bubbletea (TUI framework)", u: "https://github.com/charmbracelet/bubbletea", d: "Elm-architecture TUI framework behind Charm's tools. Worth learning.", g: ["go", "tui", "cli"] },
  { c: "Go frameworks", t: "Glow — markdown pager", u: "https://github.com/charmbracelet/glow", d: "A clean markdown pager in Go. Pleasant for reading docs.", g: ["go", "cli", "reading"] },
  { c: "Go frameworks", t: "restic — encrypted backups", u: "https://restic.net/", d: "Fast, secure, deduplicated backups written in Go.", g: ["go", "tooling", "open-source"] },
  { c: "Go frameworks", t: "fzf — fuzzy finder", u: "https://github.com/junegunn/fzf", d: "The fuzzy finder that broke into every shell. Written in Go.", g: ["go", "cli", "tooling"] },
  { c: "Go frameworks", t: "Gitea", u: "https://about.gitea.com/", d: "Lightweight self-hosted Git service in Go. A solid Forgejo alternative.", g: ["go", "self-hosted", "git"] },
  { c: "Go frameworks", t: "grpc-gateway", u: "https://grpc-ecosystem.github.io/grpc-gateway/", d: "Expose gRPC services as REST/JSON with transcoding.", g: ["go", "grpc"] },
  { c: "Go frameworks", t: "ConnectRPC for Go", u: "https://connectrpc.com/", d: "Modern protobuf-over-HTTP RPC. Simpler than gRPC, browser friendly.", g: ["go", "rpc"] },
  { c: "Go frameworks", t: "protobuf.dev", u: "https://protobuf.dev/", d: "Official Protobuf docs and cross-language programming guides.", g: ["protobuf", "docs"] },
  { c: "Go frameworks", t: "Buf Schema Registry", u: "https://buf.build/docs/", d: "Lint, break and push protobuf schemas. The modern protoc setup.", g: ["protobuf", "tooling"] },
  { c: "Go frameworks", t: "franz-go (Kafka client)", u: "https://github.com/twmb/franz-go", d: "The Kafka client most performance-minded Go teams use.", g: ["go", "kafka", "messaging"] },
  { c: "Go frameworks", t: "NATS Go client", u: "https://github.com/nats-io/nats.go", d: "Official Go client for NATS, a lean messaging system.", g: ["go", "messaging"] },
  { c: "Go frameworks", t: "WebAssembly in Go", u: "https://go.dev/wiki/WebAssembly", d: "Compiling Go to the browser with WASM. Official how-to.", g: ["go", "wasm"] },
  { c: "Go frameworks", t: "zerolog", u: "https://github.com/rs/zerolog", d: "The fastest structured logger for Go. Pair with slog or instead of it.", g: ["go", "logging", "performance"] },
  { c: "Go frameworks", t: "zap (Uber's logger)", u: "https://github.com/uber-go/zap", d: "Structured, fast, battle-tested logger with excellent docs.", g: ["go", "logging"] },
  { c: "Go frameworks", t: "CockroachDB Pebble (LSM in Go)", u: "https://github.com/cockroachdb/pebble", d: "A clean LSM key-value store in Go. Great for storage internals.", g: ["go", "databases", "storage", "code"] },
  { c: "Go frameworks", t: "NATS + Go event patterns", u: "https://docs.nats.io/", d: "NATS docs are among the best messaging docs on the web.", g: ["messaging", "docs"] },
  { c: "Go frameworks", t: "goreleaser", u: "https://goreleaser.com/", d: "Automate Go release binaries, Docker images, and multi-arch builds.", g: ["go", "release", "tooling"] },
  { c: "Go frameworks", t: "koanf configuration", u: "https://github.com/knadh/koanf", d: "Lightweight, pluggable configuration management for Go apps.", g: ["go", "config"] },
  { c: "Go frameworks", t: "Kubeshark (Go, eBPF)", u: "https://www.kubeshark.com/", d: "Service-mesh observability built on eBPF. Open-source and instructive.", g: ["go", "ebpf", "observability"] },

  { c: "Go blogs", t: "Dave Cheney — High Quality Software", u: "https://dave.cheney.net/", d: "One of the best Go blogs. GC, defer, debugging, pitfalls.", g: ["go", "blog", "must-read"] },
  { c: "Go blogs", t: "Rob Pike's Blog", u: "https://robpike.com/", d: "Go's co-creator. Lessons from 40+ years of systems work.", g: ["go", "blog", "must-read"] },
  { c: "Go blogs", t: "Ian Lance Taylor (morsedb)", u: "https://morsedb.buanzo.org/", d: "GC, allocation and runtime internals by a Go maintainer. Deep.", g: ["go", "internals", "blog"] },
  { c: "Go blogs", t: "Brad Fitzpatrick", u: "https://bradfitz.com/", d: "Go + HTTP, long-running services, and thoughtful engineering takes.", g: ["go", "blog"] },
  { c: "Go blogs", t: "Filippo Valsorda", u: "https://words.filippo.io/", d: "Go crypto, TLS, certificate internals, module supply-chain security.", g: ["go", "security", "blog", "must-read"] },
  { c: "Go blogs", t: "Dustin Ingram (di.fm)", u: "https://di.fm/", d: "Podcast and blog on distributed systems, mostly written in Go.", g: ["go", "blog", "distributed-systems"] },
  { c: "Go blogs", t: "Cloudflare Blog — tag Go", u: "https://blog.cloudflare.com/tag/go/", d: "Heavy real-world Go at massive scale. Consistently excellent.", g: ["go", "blog", "scale"] },
{ c: "Go blogs", t: "Grab Engineering Blog", u: "https://engineering.grab.com/", d: "How Grab rebuilds systems in Go, plus payments and data infra.", g: ["go", "blog", "case-study"] },
  { c: "Go blogs", t: "Zalando Engineering Blog", u: "https://engineering.zalando.com/", d: "PostgreSQL at scale, Go microservices, JVM lessons. Great archive.", g: ["go", "blog", "case-study"] },
  { c: "Go blogs", t: "Deliveroo Engineering", u: "https://deliveroo.engineering/", d: "Ruby→Go migrations, Kubernetes, resilience, mobile infra.", g: ["go", "blog", "case-study"] },
  { c: "Go blogs", t: "Monzo Technology Blog", u: "https://monzo.com/blog/technology", d: "How a bank runs on Go and Kubernetes. Honest and detailed.", g: ["go", "blog", "case-study"] },
  { c: "Go blogs", t: "Discord Engineering Blog", u: "https://discord.com/blog/engineering", d: "Rust and Go at extreme concurrency. Deep systems posts.", g: ["go", "rust", "blog", "scale"] },
  { c: "Go blogs", t: "Shopify Engineering", u: "https://shopify.engineering/", d: "Ruby→Go rewrite of the tax engine, plus perf war stories.", g: ["go", "blog", "case-study"] },
  { c: "Go blogs", t: "Tailscale blog (Go networking)", u: "https://tailscale.com/blog/", d: "Go + networking done well: netstack, tsnet, DERP. Deep but readable.", g: ["go", "networking", "blog"] },
];
