// Free & open-source learning resources — part 1: core SWE, architecture, CS fundamentals
// Fields: c = category, t = title, u = url, d = description, g = tags
const BOOKMARKS_01 = [
  { c: "Software Engineering", t: "free-programming-books", u: "https://github.com/EbookFoundation/free-programming-books", d: "The best index of free programming books, in dozens of languages.", g: ["books", "directory"] },
  { c: "Software Engineering", t: "Awesome (sindresorhus)", u: "https://github.com/sindresorhus/awesome", d: "Meta-list of curated awesome lists. The map of all maps.", g: ["list", "directory"] },
  { c: "Software Engineering", t: "The Book of Secret Knowledge", u: "https://github.com/trimstray/the-book-of-secret-knowledge", d: "Giant one-page dumping ground of tools, cheatsheets and resources.", g: ["cheatsheet", "productivity"] },
  { c: "Software Engineering", t: "system-design-primer", u: "https://github.com/donnemartin/system-design-primer", d: "Learn how to design large-scale systems. Diagrams included.", g: ["system-design", "interview"] },
  { c: "Software Engineering", t: "MIT Missing Semester", u: "https://missing.csail.mit.edu/", d: "Shells, editors, VCS, debugging, TLS, key management. Fills the CS-degree hole.", g: ["must-read", "free-course"] },
  { c: "Software Engineering", t: "The Architecture of Open Source Applications", u: "https://aosabook.org/", d: "Two free books on the architecture of real systems (Nginx, RabbitMQ...).", g: ["architecture", "books"] },
  { c: "Software Engineering", t: "Software Engineering at Google (free)", u: "https://abseil.io/resources/swe-book", d: "Full text of the SWE-at-Google book, free and legally hosted.", g: ["books", "process"] },
  { c: "Software Engineering", t: "Google SRE Book", u: "https://sre.google/sre-book/table-of-contents/", d: "What Site Reliability Engineering is, in 23 free chapters.", g: ["sre", "must-read"] },
  { c: "Software Engineering", t: "Google SRE Workbook", u: "https://sre.google/workbook/table-of-contents/", d: "Incident response, capacity planning, and the human side of SRE.", g: ["sre", "must-read"] },
  { c: "Software Engineering", t: "Refactoring Guru", u: "https://refactoring.guru/", d: "Best visual explanations of design patterns and refactoring.", g: ["patterns", "design"] },
  { c: "Software Engineering", t: "roadmap.sh", u: "https://roadmap.sh/", d: "Interactive developer roadmaps: backend, frontend, DevOps, Android, AI.", g: ["roadmap", "learning-path"] },
  { c: "Software Engineering", t: "developer-roadmap (source)", u: "https://github.com/Developer-roadmap", d: "Source repo for roadmap.sh diagrams, incl. system design.", g: ["roadmap"] },
  { c: "Software Engineering", t: "coding-interview-university", u: "https://github.com/jwasham/coding-interview-university", d: "A CS degree, self-assembled, for interviews. Huge and free.", g: ["interview", "algorithms"] },
  { c: "Software Engineering", t: "ossu/computer-science", u: "https://github.com/ossu/computer-science", d: "Complete standards-based CS curriculum using only free courses.", g: ["curriculum", "free-course"] },
  { c: "Software Engineering", t: "ossu/data-science", u: "https://github.com/ossu/data-science", d: "Same idea, for data science and ML. All free materials.", g: ["curriculum", "ml"] },
  { c: "Software Engineering", t: "The Fuzzing Book", u: "https://www.fuzzingbook.org/", d: "Everything about fuzzing, free and beautifully typeset.", g: ["security", "testing", "book"] },
  { c: "Software Engineering", t: "Notes on A Philosophy of Software Design", u: "https://www.andrewhickey.com/2019/06/19/notes-on-a-philosophy-of.html", d: "Notes on Ousterhout's deep-modules book. Pairs with Clean Architecture.", g: ["design", "book"] },
  { c: "Software Engineering", t: "37signals", u: "https://37signals.com/", d: "Essays and books (Shape Up) from a very opinionated, free blog.", g: ["process", "blog"] },
  { c: "Software Engineering", t: "Exploding Software", u: "https://explodingsoftware.com/", d: "Zachary Voase's classic essay on technical debt. Still the sharpest version.", g: ["essay", "tech-debt"] },
  { c: "Software Engineering", t: "Kent Beck archive", u: "https://www.beck.kent.edu/", d: "Essays on TDD, simplicity, and the Three/Nine/Twelve fallacy.", g: ["tdd", "essay"] },
  { c: "Software Engineering", t: "The Grug Brained Developer", u: "https://grugbrain.dev/", d: "Brutally practical, hilarious complexity-reduction guide. Read it, then delete 20% of your code.", g: ["simplicity", "must-read", "fun"] },
{ c: "Software Engineering", t: "Choose Boring Technology", u: "https://mcfunley.com/choose-boring-technology", d: "Dan McKinley on why novelty is expensive. Shapes career decisions.", g: ["architecture", "essay", "must-read"] },
  { c: "Software Engineering", t: "Write code that is easy to delete", u: "https://programmingisterrible.com/post/139222674273/how-to-write-disposable-code-in-large-systems", d: "On temporary code, over-engineering, and simplicity.", g: ["simplicity", "essay"] },
  { c: "Software Engineering", t: "Working Effectively with Legacy Code", u: "https://www.oreilly.com/library/view/working-effectively-with/0131177052/", d: "Classic seam-finding techniques. See summaries and reviews.", g: ["books", "legacy"] },
  { c: "Software Engineering", t: "Refactoring: catalog (Fowler)", u: "https://refactoring.com/catalog/", d: "The full refactoring catalog with before/after code for each move.", g: ["refactoring", "reference"] },

{ c: "Architecture", t: "The Clean Architecture (Robert C. Martin)", u: "https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html", d: "The canonical long-form post defining Clean Architecture. Start here.", g: ["clean-arch", "must-read"] },
  { c: "Architecture", t: "The Clean Coder blog", u: "https://blog.cleancoder.com/", d: "Uncle Bob on SOLID, architecture, design and agile, endlessly.", g: ["clean-arch", "blog"] },
  { c: "Architecture", t: "Hexagonal Architecture (Cockburn, original)", u: "https://alistair.cockburn.us/hexagonal-architecture/", d: "The 2000 post that coined ports & adapters. Definition with diagram.", g: ["hexagonal", "ports-adapters", "must-read"] },
{ c: "Architecture", t: "Ports & Adapters revisited (Cockburn PDF)", u: "https://alistaircockburn.com/Component%20plus%20strategy.pdf", d: "Cockburn generalises hexagonal architecture into component + strategy. Free PDF.", g: ["hexagonal", "ports-adapters"] },
  { c: "Architecture", t: "Alistair Cockburn's blog", u: "https://alistair.cockburn.us/", d: "Agile in a Nutshell, sculpting, and architecture essays.", g: ["blog", "ddd"] },
  { c: "Architecture", t: "Domain-Driven Design resources", u: "https://domaindrivendesign.org/", d: "Curated DDD articles, talks and case studies. Great entry point.", g: ["ddd", "must-read"] },
  { c: "Architecture", t: "Eric Evans — Domain Language", u: "https://www.domainlanguage.com/", d: "Evans on strategic design, bounded contexts, context maps.", g: ["ddd", "blog"] },
  { c: "Architecture", t: "microservices.io patterns", u: "https://microservices.io/patterns/", d: "Richardson's catalogue: sagas, outbox, CQRS, API gateway, idempotency.", g: ["microservices", "patterns", "must-read"] },
  { c: "Architecture", t: "Microservices (Fowler & Lewis)", u: "https://martinfowler.com/articles/microservices.html", d: "The essay that popularized microservices. Free, definitive.", g: ["microservices", "must-read"] },
  { c: "Architecture", t: "MonolithFirst (Fowler)", u: "https://martinfowler.com/bliki/MonolithFirst.html", d: "Fowler's counter-essay: start as a monolith.", g: ["monolith", "microservices"] },
{ c: "Architecture", t: "Monolith to Microservices (Fowler & Humble)", u: "https://martinfowler.com/books/", d: "Fowler and Humble on decomposition. Browse the free online chapters from the books page.", g: ["microservices", "book"] },
  { c: "Architecture", t: "Patterns of Enterprise Application Architecture", u: "https://martinfowler.com/eaaDev/", d: "The free online P of EAA catalogue. Core data-modeling patterns.", g: ["patterns", "eaa"] },
{ c: "Architecture", t: "Domain Event (Fowler EAA)", u: "https://martinfowler.com/eaaDev/DomainEvent.html", d: "Fowler on domain events, event notification and event-carried state transfer.", g: ["eda", "patterns"] },
  { c: "Architecture", t: "Onion Architecture", u: "https://www.onionsoftware.org/", d: "Jeffrey Palermo's onion variant of Clean Architecture.", g: ["onion", "clean-arch"] },
  { c: "Architecture", t: "Documenting Architecture Decisions (Nygard)", u: "https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions", d: "The original ADRs post. Short, worth every minute.", g: ["adr", "must-read"] },
  { c: "Architecture", t: "adr-tools", u: "https://github.com/npryce/adr-tools", d: "CLI to write ADRs as numbered markdown files in git.", g: ["adr", "tooling"] },
  { c: "Architecture", t: "MADR — Markdown ADRs", u: "https://adr.github.io/madr/", d: "A fuller ADR template with a status lifecycle. Good default.", g: ["adr", "template"] },
  { c: "Architecture", t: "Now in Android", u: "https://github.com/android/nowinandroid", d: "Google's flagship Kotlin app: production-grade modern architecture.", g: ["android", "kotlin", "sample-code"] },
  { c: "Architecture", t: "Android architecture samples", u: "https://github.com/android/architecture-samples", d: "Google's reference samples: MVVM/MVI, clean layers, Compose.", g: ["android", "clean-arch", "sample-code"] },
{ c: "Architecture", t: "Feature-Driven Design (Scott Cohen)", u: "https://www.featuredriven.com/", d: "A modern practical cousin of DDD by the author of the Alchemist book.", g: ["ddd"] },
  { c: "Architecture", t: "Go Clean Architecture template", u: "https://github.com/evrone/go-clean-template", d: "Opinionated Go layout: handlers → usecases → repositories.", g: ["go", "clean-arch", "template"] },
  { c: "Architecture", t: "Ardan Labs — service-driven design", u: "https://github.com/ardanlabs/service", d: "Training repo with a clean layered Go layout.", g: ["go", "clean-arch", "training"] },
{ c: "Architecture", t: "Applying Clean Architecture to Go", u: "https://manuel.kiessling.net/2012/09/28/applying-the-clean-architecture-to-go-applications/", d: "A concrete walkthrough of Clean Architecture layers in a real Go service.", g: ["go", "hexagonal"] },
  { c: "Architecture", t: "Flutter clean architecture samples", u: "https://github.com/FlutterExample", d: "Community Flutter examples incl. clean / feature-first layouts.", g: ["flutter", "sample-code"] },
  { c: "Architecture", t: "Flutterpedia (community wiki)", u: "https://flutterpedia.com/", d: "Huge community-edited Flutter knowledge base.", g: ["flutter", "wiki"] },

  { c: "CS fundamentals", t: "Operating Systems: Three Easy Pieces", u: "https://pages.cs.wisc.edu/~remzi/OSTEP/", d: "The best free OS book. Virtualization, concurrency, persistence.", g: ["os", "book", "must-read", "free"] },
  { c: "CS fundamentals", t: "MIT OpenCourseWare", u: "https://ocw.mit.edu/", d: "Free, complete university courses (CS, EE, math) with lectures + assignments.", g: ["courses", "free", "must-use"] },
  { c: "CS fundamentals", t: "Algorithms by Jeff Erickson", u: "https://jeffei.algorithms.com/", d: "Gorgeous free algorithms textbook. Highly visual and rigorous.", g: ["algorithms", "book", "free", "must-read"] },
  { c: "CS fundamentals", t: "Tim Roughgarden's theory courses", u: "https://theory.stanford.edu/", d: "Free algorithms / optimization / complexity notes. Gold standard rigor.", g: ["algorithms", "theory", "free-course", "must-read"] },
  { c: "CS fundamentals", t: "CP-Algorithms", u: "https://cp-algorithms.com/", d: "Deep algorithm dive with proofs. Excellent for competitive programming.", g: ["algorithms", "reference"] },
  { c: "CS fundamentals", t: "MIT 6.1810 Operating System Engineering", u: "https://pdos.csail.mit.edu/6.1810/", d: "Build an OS kernel (xv6) in C. Free lectures + labs. Best OS course.", g: ["os", "free-course", "systems", "must-do"] },
  { c: "CS fundamentals", t: "xv6 source (MIT)", u: "https://github.com/mit-pdos/xv6-riscv", d: "The teaching OS source. Small, clean, readable.", g: ["os", "code", "systems"] },
  { c: "CS fundamentals", t: "Visualizing Algorithms (Bret Victor)", u: "https://visualizingalgorithms.com/", d: "Animated algorithm visualizations. Brilliant pedagogy and design.", g: ["algorithms", "visualization", "fun"] },
  { c: "CS fundamentals", t: "Visualgo", u: "https://visualgo.net/", d: "Step-through visualizations of sorting, graphs, B-trees.", g: ["algorithms", "visualization"] },
  { c: "CS fundamentals", t: "Complexity Zoo", u: "https://complexityzoo.net/", d: "Fun illustrated catalogue of complexity classes. For the curious.", g: ["theory", "fun"] },
  { c: "CS fundamentals", t: "Theory of Computing (Boaz Barak)", u: "https://theoryofcomputing.org/", d: "A beautifully modern free TCS textbook. Highly recommended.", g: ["theory", "book", "free"] },
  { c: "CS fundamentals", t: "Theoretical Computer Science SE", u: "https://cstheory.stackexchange.com/", d: "Rigorous Q&A. Great for understanding CS concepts deeply.", g: ["theory", "community"] },
  { c: "CS fundamentals", t: "Berkeley CS186 (databases)", u: "https://cs186.org/", d: "Free DB internals course: indexing, query optimization, transactions. Gold.", g: ["databases", "free-course", "must-do"] },
{ c: "CS fundamentals", t: "Harvard CS50 (free)", u: "https://cs50.harvard.edu/", d: "Intro CS course fully free with lectures and problem sets. Great start.", g: ["courses", "free", "beginner"] },
  { c: "CS fundamentals", t: "freeCodeCamp", u: "https://www.freecodecamp.org/", d: "Free, project-based curriculum with certifications. Good for JS/web.", g: ["courses", "free", "web"] },
  { c: "CS fundamentals", t: "Exercism", u: "https://exercism.org/", d: "Free mentored practice problems in dozens of languages. Great for hands-on fluency.", g: ["practice", "free", "interview"] },
  { c: "CS fundamentals", t: "Project Euler", u: "https://projecteuler.net/", d: "Mathematical programming problems. Excellent mental training.", g: ["practice", "math"] },
  { c: "CS fundamentals", t: "Advent of Code", u: "https://adventofcode.com/", d: "Annual December coding puzzles. Great for learning a new language.", g: ["practice", "fun"] },
  { c: "CS fundamentals", t: "The Annotated Turing", u: "https://www.boutell.com/newton/newton.html", d: "Neil Sloane's annotated history of the Turing machine. Fascinating.", g: ["history", "fun", "must-read"] },
  { c: "CS fundamentals", t: "Big-O complexity cheatsheet", u: "https://www.bigocheatsheet.com/", d: "Complexity of common operations. Quick reference.", g: ["algorithms", "cheatsheet"] },
  { c: "CS fundamentals", t: "Stanford CS229 notes", u: "https://cs229.stanford.edu/main_notes.pdf", d: "Andrew Ng's ML course notes — the classic free ML reference.", g: ["ml", "notes"] },
  { c: "CS fundamentals", t: "Interactive linear algebra (Ben Spector)", u: "https://immersivemath.com/ila/", d: "Free interactive linear algebra textbook. Outstanding for intuition.", g: ["math", "free", "book"] }
];
