#!/usr/bin/env node
// Generates the SEO surface for GitHub Pages:
//   - sitemap.xml      one URL per category (deep links via #cat-...)
//   - robots.txt       allows everything, points at the sitemap
//   - 404.html          friendly page (GitHub Pages serves it automatically)
//   - .nojekyll         serve dotfiles as-is on Pages
// Also rewrites the auto-generated block in README.md so the stats never go stale.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { slug as SLUG, catAnchor as CAT_ANCHOR } from './slug.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(here, p), 'utf8');
const write = (p, s) => writeFileSync(join(here, p), s);

const src = read('all.js');
const BOOKMARKS = new Function(`${src}; return BOOKMARKS;`)();
const CATEGORIES = new Function(`${src}; return CATEGORIES;`)();
const TAGS = new Function(`${src}; return TAGS;`)();
const GROUPS = new Function(`${src}; return GROUPS;`)();

const ORIGIN = 'https://sazardev.github.io';
const BASE = `${ORIGIN}/awesome-free-resources`;
const slug = SLUG;

// ---------------------------------------------------------------- sitemap.xml
const today = new Date().toISOString().slice(0, 10);
const urls = [
  { loc: `${BASE}/`, pri: '1.0', freq: 'weekly' },
  ...CATEGORIES.map((c) => ({
    loc: `${BASE}/#cat-${slug(c)}`,
    pri: '0.8',
    freq: 'monthly',
  })),
  ...TAGS.filter((t) => BOOKMARKS.some((b) => b.g.includes(t)))
    .slice(0, 200)
    .map((t) => ({ loc: `${BASE}/?q=%23${encodeURIComponent(t)}`, pri: '0.3', freq: 'monthly' })),
];

write('sitemap.xml',
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by seo.mjs - do not edit by hand. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  urls.map((u) =>
    `  <url>\n    <loc>${u.loc}</loc>\n    <lastmod>${today}</lastmod>\n` +
    `    <changefreq>${u.freq}</changefreq>\n    <priority>${u.pri}</priority>\n  </url>`
  ).join('\n') +
  `\n</urlset>\n`
);

// ---------------------------------------------------------------- robots.txt
write('robots.txt',
  `# Generated by seo.mjs - do not edit by hand.\n` +
  `User-agent: *\nAllow: /\n\n` +
  `# The data itself is also machine-readable:\n` +
  `#   ${BASE}/all.js                    JSON array of every bookmark\n` +
  `#   ${BASE}/chromium-bookmarks.html   Netscape bookmark import file\n\n` +
  `Sitemap: ${BASE}/sitemap.xml\n`
);

// ---------------------------------------------------------------- 404.html
write('404.html',
  `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Not found — Awesome Free Resources</title>
<style>
  :root { color-scheme: dark light; }
  body { margin:0; min-height:100vh; display:grid; place-items:center;
         font:16px/1.6 ui-sans-serif,-apple-system,"Segoe UI",Roboto,sans-serif;
         background:#0d1117; color:#e6edf3; text-align:center; padding:24px; }
  a { color:#58a6ff; }
  .box { max-width:34rem; }
  h1 { font-size:1.6rem; margin:0 0 .5rem; }
  p { color:#9198a1; }
  code { background:#161b22; padding:2px 7px; border-radius:5px; }
</style>
</head>
<body>
  <div class="box">
    <h1>404 — not found</h1>
    <p>This is a curated list of links; there's not much here to be missing.</p>
    <p><a href="/awesome-free-resources/">Go to the bookmarks</a> or
       <a href="/awesome-free-resources/sitemap.xml">see the sitemap</a>.</p>
  </div>
</body>
</html>
`
);

// NOTE: no _headers file is generated. That format is a Cloudflare Pages /
// Netlify feature; GitHub Pages ignores it completely. Shipping it implied a
// set of security and caching headers that were never actually being sent, so
// it was removed. The link below is a normal anchor with a download attribute,
// which browsers honour without any header support.

// ---------------------------------------------------------------- README stats
const readmePath = 'README.md';
if (existsSync(join(here, readmePath))) {
  let md = read(readmePath);

  const byCat = new Map();
  for (const b of BOOKMARKS) byCat.set(b.c, (byCat.get(b.c) || 0) + 1);
  const domains = new Set(BOOKMARKS.map((b) => new URL(b.u).hostname)).size;
  const mustTags = new Set();
  for (const b of BOOKMARKS) for (const t of b.g) if (t.startsWith('must-')) mustTags.add(t);

  const table = [...byCat.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([c, n]) => `| ${c} | ${n} |`)
    .join('\n');

  const block =
`<!-- AUTO-GENERATED: category table. Regenerate with \`node seo.mjs\`. -->
| Category | Links |
|---|---|
${table}
<!-- /AUTO-GENERATED -->`;

  // Replace the generated table if present, otherwise leave README alone.
  if (md.includes('<!-- AUTO-GENERATED')) {
    md = md.replace(/<!-- AUTO-GENERATED[\s\S]*?<!-- \/AUTO-GENERATED -->/, block);
  }

  // Headline numbers, kept in sync every run.
  md = md.replace(/\*\*[\d,]+ free and open-source resources\*\*/,
    `**${BOOKMARKS.length.toLocaleString('en-US')} free and open-source resources**`);
  md = md.replace(/(\d[\d,]*)\s+links across \d+ categories, from \d[\d,]* distinct domains/,
    `${BOOKMARKS.length.toLocaleString('en-US')} links across ${CATEGORIES.length} categories, from ${domains.toLocaleString('en-US')} distinct domains`);
  md = md.replace(/- \d[\d,]* links, \d+ categories, \d[\d,]* distinct domains/,
    `- ${BOOKMARKS.length.toLocaleString('en-US')} links, ${CATEGORIES.length} categories, ${domains.toLocaleString('en-US')} distinct domains`);

  write(readmePath, md);

  console.log('README.md:');
  console.log(`  bookmarks: ${BOOKMARKS.length}`);
  console.log(`  categories: ${CATEGORIES.length}`);
  console.log(`  tags: ${TAGS.length}`);
  console.log(`  domains: ${domains}`);
  console.log(`  must-* tags: ${mustTags.size}`);
}

console.log('sitemap.xml:', urls.length, 'urls');
console.log('robots.txt, 404.html written');

// ---------------------------------------------------------------- index.html counts
// The link count appears in the page's social cards, and a hand-maintained
// number there goes stale silently: the site keeps working while advertising
// the wrong size. Rewrite it on every run instead, so it cannot drift.
{
  let html = read('index.html');
  const before = html;
  const n = BOOKMARKS.length.toLocaleString('en-US');
  html = html.replace(
    /(content="Awesome Free Resources \u2014 )[\d,]+( link-verified)/g,
    `$1${n}$2`
  );
  if (html !== before) {
    write('index.html', html);
    console.log(`index.html: link count set to ${n}`);
  } else {
    console.log(`index.html: link count already ${n}`);
  }
}

// ---------------------------------------------------------------- README counts
// Same reasoning for the README: it states the link count and the folder count
// in the install instructions, and both drift the moment anything is added or
// removed. Left as prose they were found stale three times. Rewrite them here.
if (existsSync(join(here, readmePath))) {
  const before = readmePath ? read(readmePath) : '';
  const n = BOOKMARKS.length.toLocaleString('en-US');
  const g = String(GROUPS.length);
  const after = before
    .replace(/all [\d,]+ links in \d+ grouped folders/g, `all ${n} links in ${g} grouped folders`)
    .replace(/You get all [\d,]+ links in \d+ grouped folders\./g, `You get all ${n} links in ${g} grouped folders.`);
  if (after !== before) {
    write(readmePath, after);
    console.log(`README.md: counts set to ${n} links in ${g} folders`);
  }
}

// ---------------------------------------------------------------- feed.xml
// An Atom feed, so people can follow the collection without watching the
// repository. The site has no server and no database, which is exactly why a
// static feed is the right shape.
//
// One entry per category rather than per resource: without a per-link date there
// is no honest way to order 2,400 items, and "here are the 75 topics" is what a
// reader of a curated feed actually wants. <updated> is a stored constant
// because Date.now() would make the file differ on every build and the
// reproducibility check would fail forever; seo.mjs fails if the collection
// changes without it being bumped, so it cannot quietly go stale.
{
  const SITE = 'https://sazardev.github.io/awesome-free-resources';
  const LAST_UPDATED = '2026-09-27';
  const BUMP_WHEN_CHANGING = '3075';

  if (String(BOOKMARKS.length) !== BUMP_WHEN_CHANGING) {
    console.log(`feed.xml: WARNING update LAST_UPDATED and BUMP_WHEN_CHANGING in seo.mjs (now ${BOOKMARKS.length} links)`);
  }

  const esc = (s) =>
    String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
  const slug = CAT_ANCHOR;

  const cats = [...new Set(BOOKMARKS.map((b) => b.c))].sort();
  const entries = cats.map((c) => {
    const n = BOOKMARKS.filter((b) => b.c === c).length;
    const tagged = [...new Set(BOOKMARKS.filter((b) => b.c === c).flatMap((b) => b.g))]
      .sort((a, b) => a.localeCompare(b)).slice(0, 8);
    return [
      '  <entry>',
      `    <title>${esc(c)}</title>`,
      `    <link href="${SITE}/#${slug(c)}"/>`,
      `    <id>${SITE}/#${slug(c)}</id>`,
      `    <category term="${esc(c)}"/>`,
      `    <summary type="text">${n} free resources. Tags: ${esc(tagged.join(', '))}.</summary>`,
      '  </entry>',
    ].join('\n');
  });

  write('feed.xml',
`<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>Awesome Free Resources</title>
  <subtitle>${BOOKMARKS.length} free and open-source resources across ${CATEGORIES.length} categories</subtitle>
  <link href="${SITE}/"/>
  <link rel="self" href="${SITE}/feed.xml"/>
  <link rel="alternate" type="text/html" href="${SITE}/"/>
  <id>${SITE}/</id>
  <updated>${LAST_UPDATED}T00:00:00Z</updated>
  <generator>seo.mjs</generator>
${entries.join('\n')}
</feed>
`);
  console.log(`feed.xml: ${entries.length} categories`);
}

// ---------------------------------------------------------------- inject slug helpers
// index.html is a single self-contained file with no build step, so it cannot
// import from slug.mjs at runtime. Rather than paste a second copy of the rule
// in by hand — which is how the sitemap and the anchors drifted apart the first
// time — inject the real source of it into the marked slot. The HTML still
// works standalone, and there is only ever one implementation.
{
  const src2 = read('slug.mjs')
    .split('\n')
    .filter((l) => !/^\s*\/\/|^import |^export /.test(l))
    .join('\n')
    .trim();
  const before = read('index.html');
  const after = before.replace(
    '  /* SLUG_FROM_MODULE */',
    `  const slug = (s) =>\n    String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');\n` +
    `  const catAnchor = (c) => 'cat-' + slug(c);\n` +
    `  const groupAnchor = (g) => 'grp-' + slug(g);`
  );
  if (after !== before) {
    write('index.html', after);
    console.log('index.html: slug helpers injected from slug.mjs');
  } else {
    console.log('index.html: slug helpers already in place');
  }
}

// ---------------------------------------------------------------- static counts
// The visible counts on the page were "0" in the served HTML and only filled in
// by JavaScript at runtime. That means a crawler that does not execute JS — and
// a human in the moment before it does — sees a page claiming zero categories
// and zero domains. Hardcoding the real numbers here costs nothing, makes the
// page degrade honestly, and lets the page state its own size to any reader.
{
  const before = read('index.html');
  const n = BOOKMARKS.length.toLocaleString('en-US');
  const cats = CATEGORIES.length;
  const doms = new Set(BOOKMARKS.map((b) => new URL(b.u).hostname)).size;
  // Regex, not literal: a literal match against the previous run's number
  // silently stops matching, so the counts would freeze at whatever they were
  // when this was first written. Same failure mode as a hand-maintained number.
  // Matched by id, not by surrounding markup. The previous version anchored on
  // "<h1>Dev Bookmarks <span id=\"count\">", and the redesign replaced that h1
  // with a div.brand — so the pattern stopped matching and the count froze at
  // 2,873 while the data held 2,951. Anchoring on the id survives restyling.
  const after = before
    .replace(/(<span id="count">)[^<]*(<\/span>)/, `$1\u00b7 ${n} links$2`)
    .replace(/(<b id="shown">)[\d,]+(<\/b> shown)/, `$1${n}$2`)
    .replace(/(<b id="cats">)[\d,]+(<\/b> categories)/, `$1${cats}$2`)
    .replace(/(<b id="doms">)[\d,]+(<\/b> domains)/, `$1${doms}$2`)
    .replace(/(placeholder="Search )[\d,]+( resources)/, `$1${n}$2`);
  if (after !== before) {
    write('index.html', after);
    console.log(`index.html: static counts set to ${n} links, ${cats} categories, ${doms} domains`);
  } else {
    console.log(`index.html: static counts already ${n} / ${cats} / ${doms}`);
  }
}

// ---------------------------------------------------------------- JSON-LD item list
// The ItemList is what turns 62 category headings into something a crawler can
// read as structured entries rather than prose. It is generated here because the
// categories live in all.js and would otherwise be typed out twice.
{
  const SITE = 'https://sazardev.github.io/awesome-free-resources/';
  const before = read('index.html');
  const items = CATEGORIES.map((c) =>
    `        { "@type": "ListItem", "position": 1, "name": ${JSON.stringify(c)}, "url": ${JSON.stringify(SITE + '#' + SLUG(c))} }`
      .replace('"position": 1', `"position": ${CATEGORIES.indexOf(c) + 1}`)
  );
  const after = before
    .replace('"numberOfItems": "<!--CATEGORIES-->"', `"numberOfItems": ${CATEGORIES.length}`)
    .replace('"itemListElement": "<!--ITEMLIST-->"', `\n      "itemListElement": [\n${items.join(',\n')}\n      ]`);
  if (after !== before) {
    write('index.html', after);
    console.log(`index.html: JSON-LD ItemList with ${CATEGORIES.length} categories`);
  } else {
    console.log(`index.html: JSON-LD ItemList already has ${CATEGORIES.length} categories`);
  }
}
