#!/usr/bin/env node
// Generates the SEO surface for GitHub Pages:
//   - sitemap.xml      one URL per category (deep links via #cat-...)
//   - robots.txt       allows everything, points at the sitemap
//   - 404.html          friendly page (GitHub Pages serves it automatically)
//   - .nojekyll         serve dotfiles as-is on Pages
// Also rewrites the auto-generated block in README.md so the stats never go stale.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(here, p), 'utf8');
const write = (p, s) => writeFileSync(join(here, p), s);

const src = read('all.js');
const BOOKMARKS = new Function(`${src}; return BOOKMARKS;`)();
const CATEGORIES = new Function(`${src}; return CATEGORIES;`)();
const TAGS = new Function(`${src}; return TAGS;`)();

const ORIGIN = 'https://sazardev.github.io';
const BASE = `${ORIGIN}/awesome-free-resources`;
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// ---------------------------------------------------------------- sitemap.xml
const today = new Date().toISOString().slice(0, 10);
const urls = [
  { loc: `${BASE}/`, pri: '1.0', freq: 'weekly' },
  ...CATEGORIES.map((c) => ({
    loc: `${BASE}/#cat-${slug(c)}`,
    pri: '0.8',
    freq: 'monthly',
  })),
  ...TAGS.filter((t) => BOOKMARKS.some((b) => b.g.includes(t)))
    .slice(0, 200)
    .map((t) => ({ loc: `${BASE}/?q=%23${encodeURIComponent(t)}`, pri: '0.3', freq: 'monthly' })),
];

write('sitemap.xml',
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by seo.mjs - do not edit by hand. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  urls.map((u) =>
    `  <url>\n    <loc>${u.loc}</loc>\n    <lastmod>${today}</lastmod>\n` +
    `    <changefreq>${u.freq}</changefreq>\n    <priority>${u.pri}</priority>\n  </url>`
  ).join('\n') +
  `\n</urlset>\n`
);

// ---------------------------------------------------------------- robots.txt
write('robots.txt',
  `# Generated by seo.mjs - do not edit by hand.\n` +
  `User-agent: *\nAllow: /\n\n` +
  `# The data itself is also machine-readable:\n` +
  `#   ${BASE}/all.js                    JSON array of every bookmark\n` +
  `#   ${BASE}/chromium-bookmarks.html   Netscape bookmark import file\n\n` +
  `Sitemap: ${BASE}/sitemap.xml\n`
);

// ---------------------------------------------------------------- 404.html
write('404.html',
  `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Not found — Awesome Free Resources</title>
<style>
  :root { color-scheme: dark light; }
  body { margin:0; min-height:100vh; display:grid; place-items:center;
         font:16px/1.6 ui-sans-serif,-apple-system,"Segoe UI",Roboto,sans-serif;
         background:#0d1117; color:#e6edf3; text-align:center; padding:24px; }
  a { color:#58a6ff; }
  .box { max-width:34rem; }
  h1 { font-size:1.6rem; margin:0 0 .5rem; }
  p { color:#9198a1; }
  code { background:#161b22; padding:2px 7px; border-radius:5px; }
</style>
</head>
<body>
  <div class="box">
    <h1>404 — not found</h1>
    <p>This is a curated list of links; there's not much here to be missing.</p>
    <p><a href="/awesome-free-resources/">Go to the bookmarks</a> or
       <a href="/awesome-free-resources/sitemap.xml">see the sitemap</a>.</p>
  </div>
</body>
</html>
`
);

// NOTE: no _headers file is generated. That format is a Cloudflare Pages /
// Netlify feature; GitHub Pages ignores it completely. Shipping it implied a
// set of security and caching headers that were never actually being sent, so
// it was removed. The link below is a normal anchor with a download attribute,
// which browsers honour without any header support.

// ---------------------------------------------------------------- README stats
const readmePath = 'README.md';
if (existsSync(join(here, readmePath))) {
  let md = read(readmePath);

  const byCat = new Map();
  for (const b of BOOKMARKS) byCat.set(b.c, (byCat.get(b.c) || 0) + 1);
  const domains = new Set(BOOKMARKS.map((b) => new URL(b.u).hostname)).size;
  const mustTags = new Set();
  for (const b of BOOKMARKS) for (const t of b.g) if (t.startsWith('must-')) mustTags.add(t);

  const table = [...byCat.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([c, n]) => `| ${c} | ${n} |`)
    .join('\n');

  const block =
`<!-- AUTO-GENERATED: category table. Regenerate with \`node seo.mjs\`. -->
| Category | Links |
|---|---|
${table}
<!-- /AUTO-GENERATED -->`;

  // Replace the generated table if present, otherwise leave README alone.
  if (md.includes('<!-- AUTO-GENERATED')) {
    md = md.replace(/<!-- AUTO-GENERATED[\s\S]*?<!-- \/AUTO-GENERATED -->/, block);
  }

  // Headline numbers, kept in sync every run.
  md = md.replace(/\*\*[\d,]+ free and open-source resources\*\*/,
    `**${BOOKMARKS.length.toLocaleString('en-US')} free and open-source resources**`);
  md = md.replace(/(\d[\d,]*)\s+links across \d+ categories, from \d[\d,]* distinct domains/,
    `${BOOKMARKS.length.toLocaleString('en-US')} links across ${CATEGORIES.length} categories, from ${domains.toLocaleString('en-US')} distinct domains`);
  md = md.replace(/- \d[\d,]* links, \d+ categories, \d[\d,]* distinct domains/,
    `- ${BOOKMARKS.length.toLocaleString('en-US')} links, ${CATEGORIES.length} categories, ${domains.toLocaleString('en-US')} distinct domains`);

  write(readmePath, md);

  console.log('README.md:');
  console.log(`  bookmarks: ${BOOKMARKS.length}`);
  console.log(`  categories: ${CATEGORIES.length}`);
  console.log(`  tags: ${TAGS.length}`);
  console.log(`  domains: ${domains}`);
  console.log(`  must-* tags: ${mustTags.size}`);
}

console.log('sitemap.xml:', urls.length, 'urls');
console.log('robots.txt, 404.html written');

// ---------------------------------------------------------------- index.html counts
// The link count appears in the page's social cards, and a hand-maintained
// number there goes stale silently: the site keeps working while advertising
// the wrong size. Rewrite it on every run instead, so it cannot drift.
{
  let html = read('index.html');
  const before = html;
  const n = BOOKMARKS.length.toLocaleString('en-US');
  html = html.replace(
    /(content="Awesome Free Resources \u2014 )[\d,]+( link-verified)/g,
    `$1${n}$2`
  );
  if (html !== before) {
    write('index.html', html);
    console.log(`index.html: link count set to ${n}`);
  } else {
    console.log(`index.html: link count already ${n}`);
  }
}
